package org.bayisehat.rdb2fhir.core.example.r4;

import org.bayisehat.rdb2fhir.core.example.BaseExampleTest;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

public class FamilyToOxygenGroup extends BaseExampleTest {

    @Test  void familymemberhistory_example_mother() throws Exception { assertEqual("familymemberhistory-example-mother.json"); }
    @Test  void familymemberhistory_example() throws Exception { assertEqual("familymemberhistory-example.json"); }
    @Test  void familymemberhistory_genetic_questionnaire() throws Exception { assertEqual("familymemberhistory-genetic-questionnaire.json"); }
    @Test  void familymemberhistory_genetic_profile() throws Exception { assertEqual("familymemberhistory-genetic.profile.json"); }
    @Test  void familymemberhistory_questionnaire() throws Exception { assertEqual("familymemberhistory-questionnaire.json"); }
    @Test  void familymemberhistory_profile() throws Exception { assertEqual("familymemberhistory.profile.json"); }
    @Test @Tag("multi")  void fivews() throws Exception { assertEqual("fivews.json"); }
    @Test  void flag_example_encounter() throws Exception { assertEqual("flag-example-encounter.json"); }
    @Test  void flag_example() throws Exception { assertEqual("flag-example.json"); }
    @Test  void flag_questionnaire() throws Exception { assertEqual("flag-questionnaire.json"); }
    @Test  void flag_profile() throws Exception { assertEqual("flag.profile.json"); }
    @Test  void goal_example_stop_smoking() throws Exception { assertEqual("goal-example-stop-smoking.json"); }
    @Test  void goal_example() throws Exception { assertEqual("goal-example.json"); }
    @Test  void goal_questionnaire() throws Exception { assertEqual("goal-questionnaire.json"); }
    @Test  void goal_profile() throws Exception { assertEqual("goal.profile.json"); }
    @Test  void graphdefinition_example() throws Exception { assertEqual("graphdefinition-example.json"); }
    @Test  void graphdefinition_questionnaire() throws Exception { assertEqual("graphdefinition-questionnaire.json"); }
    @Test  void graphdefinition_profile() throws Exception { assertEqual("graphdefinition.profile.json"); }
    @Test  void group_example_herd1() throws Exception { assertEqual("group-example-herd1.json"); }
    @Test  void group_example_member() throws Exception { assertEqual("group-example-member.json"); }
    @Test  void group_example_patientlist() throws Exception { assertEqual("group-example-patientlist.json"); }
    @Test  void group_example() throws Exception { assertEqual("group-example.json"); }
    @Test  void group_questionnaire() throws Exception { assertEqual("group-questionnaire.json"); }
    @Test  void group_profile() throws Exception { assertEqual("group.profile.json"); }
    @Test  void groupdefinition_questionnaire() throws Exception { assertEqual("groupdefinition-questionnaire.json"); }
    @Test  void groupdefinition_profile() throws Exception { assertEqual("groupdefinition.profile.json"); }
    @Test  void guidanceresponse_example() throws Exception { assertEqual("guidanceresponse-example.json"); }
    @Test  void guidanceresponse_questionnaire() throws Exception { assertEqual("guidanceresponse-questionnaire.json"); }
    @Test  void guidanceresponse_profile() throws Exception { assertEqual("guidanceresponse.profile.json"); }
    @Test  void hdlcholesterol_questionnaire() throws Exception { assertEqual("hdlcholesterol-questionnaire.json"); }
    @Test  void hdlcholesterol_profile() throws Exception { assertEqual("hdlcholesterol.profile.json"); }
    @Test  void headcircum_questionnaire() throws Exception { assertEqual("headcircum-questionnaire.json"); }
    @Test  void headcircum_profile() throws Exception { assertEqual("headcircum.profile.json"); }
    @Test  void healthcareservice_example() throws Exception { assertEqual("healthcareservice-example.json"); }
    @Test  void healthcareservice_questionnaire() throws Exception { assertEqual("healthcareservice-questionnaire.json"); }
    @Test  void healthcareservice_profile() throws Exception { assertEqual("healthcareservice.profile.json"); }
    @Test  void heartrate_questionnaire() throws Exception { assertEqual("heartrate-questionnaire.json"); }
    @Test  void heartrate_profile() throws Exception { assertEqual("heartrate.profile.json"); }
    @Test  void hlaresult_questionnaire() throws Exception { assertEqual("hlaresult-questionnaire.json"); }
    @Test  void hlaresult_profile() throws Exception { assertEqual("hlaresult.profile.json"); }
    @Test @Tag("multi")  void humanname_profile() throws Exception { assertEqual("humanname.profile.json"); }
    @Test  void id_profile() throws Exception { assertEqual("id.profile.json"); }
    @Test  void identifier_profile() throws Exception { assertEqual("identifier.profile.json"); }
    @Test  void imagingstudy_example_xr() throws Exception { assertEqual("imagingstudy-example-xr.json"); }
    @Test  void imagingstudy_example() throws Exception { assertEqual("imagingstudy-example.json"); }
    @Test  void imagingstudy_questionnaire() throws Exception { assertEqual("imagingstudy-questionnaire.json"); }
    @Test  void imagingstudy_profile() throws Exception { assertEqual("imagingstudy.profile.json"); }
    @Test  void immunization_example_historical() throws Exception { assertEqual("immunization-example-historical.json"); }
    @Test  void immunization_example_protocol() throws Exception { assertEqual("immunization-example-protocol.json"); }
    @Test  void immunization_example_refused() throws Exception { assertEqual("immunization-example-refused.json"); }
    @Test  void immunization_example_subpotent() throws Exception { assertEqual("immunization-example-subpotent.json"); }
    @Test  void immunization_example() throws Exception { assertEqual("immunization-example.json"); }
    @Test  void immunization_questionnaire() throws Exception { assertEqual("immunization-questionnaire.json"); }
    @Test  void immunization_profile() throws Exception { assertEqual("immunization.profile.json"); }
    @Test  void immunizationevaluation_example_notvalid() throws Exception { assertEqual("immunizationevaluation-example-notvalid.json"); }
    @Test  void immunizationevaluation_example() throws Exception { assertEqual("immunizationevaluation-example.json"); }
    @Test  void immunizationevaluation_questionnaire() throws Exception { assertEqual("immunizationevaluation-questionnaire.json"); }
    @Test  void immunizationevaluation_profile() throws Exception { assertEqual("immunizationevaluation.profile.json"); }
    @Test  void immunizationrecommendation_example_target_disease() throws Exception { assertEqual("immunizationrecommendation-example-target-disease.json"); }
    @Test  void immunizationrecommendation_example() throws Exception { assertEqual("immunizationrecommendation-example.json"); }
    @Test  void immunizationrecommendation_questionnaire() throws Exception { assertEqual("immunizationrecommendation-questionnaire.json"); }
    @Test  void immunizationrecommendation_profile() throws Exception { assertEqual("immunizationrecommendation.profile.json"); }
    @Test  void implementationguide_example() throws Exception { assertEqual("implementationguide-example.json"); }
    @Test  void implementationguide_questionnaire() throws Exception { assertEqual("implementationguide-questionnaire.json"); }
    @Test  void implementationguide_profile() throws Exception { assertEqual("implementationguide.profile.json"); }
    @Test  void instant_profile() throws Exception { assertEqual("instant.profile.json"); }
    @Test  void insuranceplan_example() throws Exception { assertEqual("insuranceplan-example.json"); }
    @Test  void insuranceplan_questionnaire() throws Exception { assertEqual("insuranceplan-questionnaire.json"); }
    @Test  void insuranceplan_profile() throws Exception { assertEqual("insuranceplan.profile.json"); }
    @Test  void integer_profile() throws Exception { assertEqual("integer.profile.json"); }
    @Test  void invoice_example() throws Exception { assertEqual("invoice-example.json"); }
    @Test  void invoice_questionnaire() throws Exception { assertEqual("invoice-questionnaire.json"); }
    @Test  void invoice_profile() throws Exception { assertEqual("invoice.profile.json"); }
    @Test  void json_edge_cases() throws Exception { assertEqual("json-edge-cases.json"); }
    @Test  void ldlcholesterol_questionnaire() throws Exception { assertEqual("ldlcholesterol-questionnaire.json"); }
    @Test  void ldlcholesterol_profile() throws Exception { assertEqual("ldlcholesterol.profile.json"); }
    @Test  void library_cms146_example() throws Exception { assertEqual("library-cms146-example.json"); }
    @Test  void library_composition_example() throws Exception { assertEqual("library-composition-example.json"); }
    @Test  void library_example() throws Exception { assertEqual("library-example.json"); }
    @Test  void library_exclusive_breastfeeding_cds_logic() throws Exception { assertEqual("library-exclusive-breastfeeding-cds-logic.json"); }
    @Test  void library_exclusive_breastfeeding_cqm_logic() throws Exception { assertEqual("library-exclusive-breastfeeding-cqm-logic.json"); }
    @Test  void library_fhir_helpers() throws Exception { assertEqual("library-fhir-helpers.json"); }
    @Test  void library_fhir_model_definition() throws Exception { assertEqual("library-fhir-model-definition.json"); }
    @Test  void library_hiv_indicators() throws Exception { assertEqual("library-hiv-indicators.json"); }
    @Test  void library_mmi_suiciderisk_orderset_logic() throws Exception { assertEqual("library-mmi-suiciderisk-orderset-logic.json"); }
    @Test  void library_omtk_logic() throws Exception { assertEqual("library-omtk-logic.json"); }
    @Test  void library_omtk_modelinfo() throws Exception { assertEqual("library-omtk-modelinfo.json"); }
    @Test  void library_opioidcds_common() throws Exception { assertEqual("library-opioidcds-common.json"); }
    @Test  void library_opioidcds_recommendation_04() throws Exception { assertEqual("library-opioidcds-recommendation-04.json"); }
    @Test  void library_opioidcds_recommendation_05() throws Exception { assertEqual("library-opioidcds-recommendation-05.json"); }
    @Test  void library_opioidcds_recommendation_07() throws Exception { assertEqual("library-opioidcds-recommendation-07.json"); }
    @Test  void library_opioidcds_recommendation_08() throws Exception { assertEqual("library-opioidcds-recommendation-08.json"); }
    @Test  void library_opioidcds_recommendation_10() throws Exception { assertEqual("library-opioidcds-recommendation-10.json"); }
    @Test  void library_opioidcds_recommendation_11() throws Exception { assertEqual("library-opioidcds-recommendation-11.json"); }
    @Test  void library_predecessor_example() throws Exception { assertEqual("library-predecessor-example.json"); }
    @Test  void library_questionnaire() throws Exception { assertEqual("library-questionnaire.json"); }
    @Test  void library_quick_model_definition() throws Exception { assertEqual("library-quick-model-definition.json"); }
    @Test  void library_zika_virus_intervention_logic() throws Exception { assertEqual("library-zika-virus-intervention-logic.json"); }
    @Test  void library_profile() throws Exception { assertEqual("library.profile.json"); }
    @Test  void linkage_example() throws Exception { assertEqual("linkage-example.json"); }
    @Test  void linkage_questionnaire() throws Exception { assertEqual("linkage-questionnaire.json"); }
    @Test  void linkage_profile() throws Exception { assertEqual("linkage.profile.json"); }
    @Test  void lipidprofile_questionnaire() throws Exception { assertEqual("lipidprofile-questionnaire.json"); }
    @Test  void lipidprofile_profile() throws Exception { assertEqual("lipidprofile.profile.json"); }
    @Test  void list_example_allergies() throws Exception { assertEqual("list-example-allergies.json"); }
    @Test  void list_example_double_cousin_relationship_pedigree() throws Exception { assertEqual("list-example-double-cousin-relationship-pedigree.json"); }
    @Test  void list_example_empty() throws Exception { assertEqual("list-example-empty.json"); }
    @Test  void list_example_familyhistory_f201_roel() throws Exception { assertEqual("list-example-familyhistory-f201-roel.json"); }
    @Test @Tag("multi")  void list_example_familyhistory_genetics_profile_annie() throws Exception { assertEqual("list-example-familyhistory-genetics-profile-annie.json"); }
    @Test @Tag("multi")  void list_example_familyhistory_genetics_profile() throws Exception { assertEqual("list-example-familyhistory-genetics-profile.json"); }
    @Test @Tag("multi")  void list_example_long() throws Exception { assertEqual("list-example-long.json"); }
    @Test  void list_example_medlist() throws Exception { assertEqual("list-example-medlist.json"); }
    @Test  void list_example_simple_empty() throws Exception { assertEqual("list-example-simple-empty.json"); }
    @Test  void list_example() throws Exception { assertEqual("list-example.json"); }
    @Test  void list_questionnaire() throws Exception { assertEqual("list-questionnaire.json"); }
    @Test  void list_profile() throws Exception { assertEqual("list.profile.json"); }
    @Test  void location_example_ambulance() throws Exception { assertEqual("location-example-ambulance.json"); }
    @Test  void location_example_hl7hq() throws Exception { assertEqual("location-example-hl7hq.json"); }
    @Test  void location_example_patients_home() throws Exception { assertEqual("location-example-patients-home.json"); }
    @Test  void location_example_room() throws Exception { assertEqual("location-example-room.json"); }
    @Test  void location_example_ukpharmacy() throws Exception { assertEqual("location-example-ukpharmacy.json"); }
    @Test  void location_example() throws Exception { assertEqual("location-example.json"); }
    @Test @Tag("bundle")  void location_examples_general() throws Exception { assertEqual("location-examples-general.json"); }
    @Test  void location_questionnaire() throws Exception { assertEqual("location-questionnaire.json"); }
    @Test  void location_profile() throws Exception { assertEqual("location.profile.json"); }
    @Test  void markdown_profile() throws Exception { assertEqual("markdown.profile.json"); }
    @Test @Tag("multi")  void marketingstatus_profile() throws Exception { assertEqual("marketingstatus.profile.json"); }
    @Test  void measure_cms146_example() throws Exception { assertEqual("measure-cms146-example.json"); }
    @Test  void measure_component_a_example() throws Exception { assertEqual("measure-component-a-example.json"); }
    @Test  void measure_component_b_example() throws Exception { assertEqual("measure-component-b-example.json"); }
    @Test  void measure_composite_example() throws Exception { assertEqual("measure-composite-example.json"); }
    @Test @Tag("multi")  void measure_exclusive_breastfeeding() throws Exception { assertEqual("measure-exclusive-breastfeeding.json"); }
    @Test @Tag("multi")  void measure_hiv_indicators() throws Exception { assertEqual("measure-hiv-indicators.json"); }
    @Test @Tag("multi")  void measure_predecessor_example() throws Exception { assertEqual("measure-predecessor-example.json"); }
    @Test  void measure_questionnaire() throws Exception { assertEqual("measure-questionnaire.json"); }
    @Test  void measure_profile() throws Exception { assertEqual("measure.profile.json"); }
    @Test  void measurereport_cms146_cat1_example() throws Exception { assertEqual("measurereport-cms146-cat1-example.json"); }
    @Test  void measurereport_cms146_cat2_example() throws Exception { assertEqual("measurereport-cms146-cat2-example.json"); }
    @Test  void measurereport_cms146_cat3_example() throws Exception { assertEqual("measurereport-cms146-cat3-example.json"); }
    @Test  void measurereport_hiv_indicators() throws Exception { assertEqual("measurereport-hiv-indicators.json"); }
    @Test  void measurereport_questionnaire() throws Exception { assertEqual("measurereport-questionnaire.json"); }
    @Test  void measurereport_profile() throws Exception { assertEqual("measurereport.profile.json"); }
    @Test  void media_example_dicom() throws Exception { assertEqual("media-example-dicom.json"); }
    @Test  void media_example_sound() throws Exception { assertEqual("media-example-sound.json"); }
    @Test  void media_example_xray() throws Exception { assertEqual("media-example-xray.json"); }
    @Test  void media_example() throws Exception { assertEqual("media-example.json"); }
    @Test  void media_questionnaire() throws Exception { assertEqual("media-questionnaire.json"); }
    @Test  void media_profile() throws Exception { assertEqual("media.profile.json"); }
    @Test  void medication_questionnaire() throws Exception { assertEqual("medication-questionnaire.json"); }
    @Test  void medication_profile() throws Exception { assertEqual("medication.profile.json"); }
    @Test  void medicationadministration_questionnaire() throws Exception { assertEqual("medicationadministration-questionnaire.json"); }
    @Test  void medicationadministration_profile() throws Exception { assertEqual("medicationadministration.profile.json"); }
    @Test  void medicationadministration0301() throws Exception { assertEqual("medicationadministration0301.json"); }
    @Test  void medicationadministration0302() throws Exception { assertEqual("medicationadministration0302.json"); }
    @Test  void medicationadministration0303() throws Exception { assertEqual("medicationadministration0303.json"); }
    @Test  void medicationadministration0304() throws Exception { assertEqual("medicationadministration0304.json"); }
    @Test  void medicationadministration0305() throws Exception { assertEqual("medicationadministration0305.json"); }
    @Test  void medicationadministration0306() throws Exception { assertEqual("medicationadministration0306.json"); }
    @Test  void medicationadministration0307() throws Exception { assertEqual("medicationadministration0307.json"); }
    @Test  void medicationadministration0308() throws Exception { assertEqual("medicationadministration0308.json"); }
    @Test  void medicationadministration0309() throws Exception { assertEqual("medicationadministration0309.json"); }
    @Test  void medicationadministration0310() throws Exception { assertEqual("medicationadministration0310.json"); }
    @Test  void medicationadministration0311() throws Exception { assertEqual("medicationadministration0311.json"); }
    @Test  void medicationadministration0312() throws Exception { assertEqual("medicationadministration0312.json"); }
    @Test  void medicationadministration0313() throws Exception { assertEqual("medicationadministration0313.json"); }
    @Test  void medicationadministrationexample3() throws Exception { assertEqual("medicationadministrationexample3.json"); }
    @Test  void medicationdispense_questionnaire() throws Exception { assertEqual("medicationdispense-questionnaire.json"); }
    @Test  void medicationdispense_profile() throws Exception { assertEqual("medicationdispense.profile.json"); }
    @Test  void medicationdispense0301() throws Exception { assertEqual("medicationdispense0301.json"); }
    @Test  void medicationdispense0302() throws Exception { assertEqual("medicationdispense0302.json"); }
    @Test  void medicationdispense0303() throws Exception { assertEqual("medicationdispense0303.json"); }
    @Test  void medicationdispense0304() throws Exception { assertEqual("medicationdispense0304.json"); }
    @Test  void medicationdispense0305() throws Exception { assertEqual("medicationdispense0305.json"); }
    @Test  void medicationdispense0306() throws Exception { assertEqual("medicationdispense0306.json"); }
    @Test  void medicationdispense0307() throws Exception { assertEqual("medicationdispense0307.json"); }
    @Test  void medicationdispense0308() throws Exception { assertEqual("medicationdispense0308.json"); }
    @Test  void medicationdispense0309() throws Exception { assertEqual("medicationdispense0309.json"); }
    @Test  void medicationdispense0310() throws Exception { assertEqual("medicationdispense0310.json"); }
    @Test  void medicationdispense0311() throws Exception { assertEqual("medicationdispense0311.json"); }
    @Test  void medicationdispense0312() throws Exception { assertEqual("medicationdispense0312.json"); }
    @Test  void medicationdispense0313() throws Exception { assertEqual("medicationdispense0313.json"); }
    @Test  void medicationdispense0314() throws Exception { assertEqual("medicationdispense0314.json"); }
    @Test  void medicationdispense0315() throws Exception { assertEqual("medicationdispense0315.json"); }
    @Test  void medicationdispense0316() throws Exception { assertEqual("medicationdispense0316.json"); }
    @Test  void medicationdispense0317() throws Exception { assertEqual("medicationdispense0317.json"); }
    @Test  void medicationdispense0318() throws Exception { assertEqual("medicationdispense0318.json"); }
    @Test  void medicationdispense0319() throws Exception { assertEqual("medicationdispense0319.json"); }
    @Test  void medicationdispense0320() throws Exception { assertEqual("medicationdispense0320.json"); }
    @Test  void medicationdispense0321() throws Exception { assertEqual("medicationdispense0321.json"); }
    @Test  void medicationdispense0322() throws Exception { assertEqual("medicationdispense0322.json"); }
    @Test  void medicationdispense0324() throws Exception { assertEqual("medicationdispense0324.json"); }
    @Test  void medicationdispense0325() throws Exception { assertEqual("medicationdispense0325.json"); }
    @Test  void medicationdispense0326() throws Exception { assertEqual("medicationdispense0326.json"); }
    @Test  void medicationdispense0327() throws Exception { assertEqual("medicationdispense0327.json"); }
    @Test  void medicationdispense0328() throws Exception { assertEqual("medicationdispense0328.json"); }
    @Test  void medicationdispense0329() throws Exception { assertEqual("medicationdispense0329.json"); }
    @Test  void medicationdispense0330() throws Exception { assertEqual("medicationdispense0330.json"); }
    @Test  void medicationdispense0331() throws Exception { assertEqual("medicationdispense0331.json"); }
    @Test  void medicationdispenseexample8() throws Exception { assertEqual("medicationdispenseexample8.json"); }
    @Test  void medicationexample0301() throws Exception { assertEqual("medicationexample0301.json"); }
    @Test  void medicationexample0302() throws Exception { assertEqual("medicationexample0302.json"); }
    @Test  void medicationexample0303() throws Exception { assertEqual("medicationexample0303.json"); }
    @Test  void medicationexample0304() throws Exception { assertEqual("medicationexample0304.json"); }
    @Test  void medicationexample0305() throws Exception { assertEqual("medicationexample0305.json"); }
    @Test  void medicationexample0306() throws Exception { assertEqual("medicationexample0306.json"); }
    @Test  void medicationexample0307() throws Exception { assertEqual("medicationexample0307.json"); }
    @Test  void medicationexample0308() throws Exception { assertEqual("medicationexample0308.json"); }
    @Test  void medicationexample0309() throws Exception { assertEqual("medicationexample0309.json"); }
    @Test  void medicationexample0310() throws Exception { assertEqual("medicationexample0310.json"); }
    @Test  void medicationexample0311() throws Exception { assertEqual("medicationexample0311.json"); }
    @Test  void medicationexample0312() throws Exception { assertEqual("medicationexample0312.json"); }
    @Test  void medicationexample0313() throws Exception { assertEqual("medicationexample0313.json"); }
    @Test  void medicationexample0314() throws Exception { assertEqual("medicationexample0314.json"); }
    @Test  void medicationexample0315() throws Exception { assertEqual("medicationexample0315.json"); }
    @Test  void medicationexample0316() throws Exception { assertEqual("medicationexample0316.json"); }
    @Test  void medicationexample0317() throws Exception { assertEqual("medicationexample0317.json"); }
    @Test  void medicationexample0318() throws Exception { assertEqual("medicationexample0318.json"); }
    @Test  void medicationexample0319() throws Exception { assertEqual("medicationexample0319.json"); }
    @Test  void medicationexample0320() throws Exception { assertEqual("medicationexample0320.json"); }
    @Test  void medicationexample0321() throws Exception { assertEqual("medicationexample0321.json"); }
    @Test  void medicationexample1() throws Exception { assertEqual("medicationexample1.json"); }
    @Test  void medicationexample15() throws Exception { assertEqual("medicationexample15.json"); }
    @Test  void medicationknowledge_example() throws Exception { assertEqual("medicationknowledge-example.json"); }
    @Test  void medicationknowledge_questionnaire() throws Exception { assertEqual("medicationknowledge-questionnaire.json"); }
    @Test  void medicationknowledge_profile() throws Exception { assertEqual("medicationknowledge.profile.json"); }
    @Test  void medicationrequest_questionnaire() throws Exception { assertEqual("medicationrequest-questionnaire.json"); }
    @Test  void medicationrequest_profile() throws Exception { assertEqual("medicationrequest.profile.json"); }
    @Test  void medicationrequest0301() throws Exception { assertEqual("medicationrequest0301.json"); }
    @Test  void medicationrequest0302() throws Exception { assertEqual("medicationrequest0302.json"); }
    @Test  void medicationrequest0303() throws Exception { assertEqual("medicationrequest0303.json"); }
    @Test  void medicationrequest0304() throws Exception { assertEqual("medicationrequest0304.json"); }
    @Test  void medicationrequest0305() throws Exception { assertEqual("medicationrequest0305.json"); }
    @Test  void medicationrequest0306() throws Exception { assertEqual("medicationrequest0306.json"); }
    @Test  void medicationrequest0307() throws Exception { assertEqual("medicationrequest0307.json"); }
    @Test  void medicationrequest0308() throws Exception { assertEqual("medicationrequest0308.json"); }
    @Test  void medicationrequest0309() throws Exception { assertEqual("medicationrequest0309.json"); }
    @Test  void medicationrequest0310() throws Exception { assertEqual("medicationrequest0310.json"); }
    @Test  void medicationrequest0312() throws Exception { assertEqual("medicationrequest0312.json"); }
    @Test  void medicationrequest0313() throws Exception { assertEqual("medicationrequest0313.json"); }
    @Test  void medicationrequest0314() throws Exception { assertEqual("medicationrequest0314.json"); }
    @Test  void medicationrequest0315() throws Exception { assertEqual("medicationrequest0315.json"); }
    @Test  void medicationrequest0316() throws Exception { assertEqual("medicationrequest0316.json"); }
    @Test  void medicationrequest0317() throws Exception { assertEqual("medicationrequest0317.json"); }
    @Test  void medicationrequest0318() throws Exception { assertEqual("medicationrequest0318.json"); }
    @Test  void medicationrequest0319() throws Exception { assertEqual("medicationrequest0319.json"); }
    @Test  void medicationrequest0320() throws Exception { assertEqual("medicationrequest0320.json"); }
    @Test  void medicationrequest0321() throws Exception { assertEqual("medicationrequest0321.json"); }
    @Test  void medicationrequest0322() throws Exception { assertEqual("medicationrequest0322.json"); }
    @Test  void medicationrequest0323() throws Exception { assertEqual("medicationrequest0323.json"); }
    @Test  void medicationrequest0324() throws Exception { assertEqual("medicationrequest0324.json"); }
    @Test  void medicationrequest0325() throws Exception { assertEqual("medicationrequest0325.json"); }
    @Test  void medicationrequest0326() throws Exception { assertEqual("medicationrequest0326.json"); }
    @Test  void medicationrequest0327() throws Exception { assertEqual("medicationrequest0327.json"); }
    @Test  void medicationrequest0328() throws Exception { assertEqual("medicationrequest0328.json"); }
    @Test  void medicationrequest0329() throws Exception { assertEqual("medicationrequest0329.json"); }
    @Test  void medicationrequest0330() throws Exception { assertEqual("medicationrequest0330.json"); }
    @Test  void medicationrequest0331() throws Exception { assertEqual("medicationrequest0331.json"); }
    @Test  void medicationrequest0332() throws Exception { assertEqual("medicationrequest0332.json"); }
    @Test  void medicationrequest0333() throws Exception { assertEqual("medicationrequest0333.json"); }
    @Test  void medicationrequest0334() throws Exception { assertEqual("medicationrequest0334.json"); }
    @Test  void medicationrequest0335() throws Exception { assertEqual("medicationrequest0335.json"); }
    @Test  void medicationrequest0336() throws Exception { assertEqual("medicationrequest0336.json"); }
    @Test  void medicationrequest0337() throws Exception { assertEqual("medicationrequest0337.json"); }
    @Test  void medicationrequest0338() throws Exception { assertEqual("medicationrequest0338.json"); }
    @Test  void medicationrequest0339() throws Exception { assertEqual("medicationrequest0339.json"); }
    @Test  void medicationrequestexample1() throws Exception { assertEqual("medicationrequestexample1.json"); }
    @Test  void medicationrequestexample2() throws Exception { assertEqual("medicationrequestexample2.json"); }
    @Test  void medicationstatement_questionnaire() throws Exception { assertEqual("medicationstatement-questionnaire.json"); }
    @Test  void medicationstatement_profile() throws Exception { assertEqual("medicationstatement.profile.json"); }
    @Test  void medicationstatementexample1() throws Exception { assertEqual("medicationstatementexample1.json"); }
    @Test  void medicationstatementexample2() throws Exception { assertEqual("medicationstatementexample2.json"); }
    @Test  void medicationstatementexample3() throws Exception { assertEqual("medicationstatementexample3.json"); }
    @Test  void medicationstatementexample4() throws Exception { assertEqual("medicationstatementexample4.json"); }
    @Test  void medicationstatementexample5() throws Exception { assertEqual("medicationstatementexample5.json"); }
    @Test  void medicationstatementexample6() throws Exception { assertEqual("medicationstatementexample6.json"); }
    @Test  void medicationstatementexample7() throws Exception { assertEqual("medicationstatementexample7.json"); }
    @Test  void medicinalproduct_example() throws Exception { assertEqual("medicinalproduct-example.json"); }
    @Test  void medicinalproduct_questionnaire() throws Exception { assertEqual("medicinalproduct-questionnaire.json"); }
    @Test @Tag("multi")  void medicinalproduct_profile() throws Exception { assertEqual("medicinalproduct.profile.json"); }
    @Test  void medicinalproductauthorization_example() throws Exception { assertEqual("medicinalproductauthorization-example.json"); }
    @Test  void medicinalproductauthorization_questionnaire() throws Exception { assertEqual("medicinalproductauthorization-questionnaire.json"); }
    @Test @Tag("multi")  void medicinalproductauthorization_profile() throws Exception { assertEqual("medicinalproductauthorization.profile.json"); }
    @Test  void medicinalproductcontraindication_example() throws Exception { assertEqual("medicinalproductcontraindication-example.json"); }
    @Test  void medicinalproductcontraindication_questionnaire() throws Exception { assertEqual("medicinalproductcontraindication-questionnaire.json"); }
    @Test @Tag("multi")  void medicinalproductcontraindication_profile() throws Exception { assertEqual("medicinalproductcontraindication.profile.json"); }
    @Test  void medicinalproductindication_example() throws Exception { assertEqual("medicinalproductindication-example.json"); }
    @Test  void medicinalproductindication_questionnaire() throws Exception { assertEqual("medicinalproductindication-questionnaire.json"); }
    @Test @Tag("multi")  void medicinalproductindication_profile() throws Exception { assertEqual("medicinalproductindication.profile.json"); }
    @Test  void medicinalproductingredient_example() throws Exception { assertEqual("medicinalproductingredient-example.json"); }
    @Test  void medicinalproductingredient_questionnaire() throws Exception { assertEqual("medicinalproductingredient-questionnaire.json"); }
    @Test @Tag("multi")  void medicinalproductingredient_profile() throws Exception { assertEqual("medicinalproductingredient.profile.json"); }
    @Test  void medicinalproductinteraction_example() throws Exception { assertEqual("medicinalproductinteraction-example.json"); }
    @Test  void medicinalproductinteraction_questionnaire() throws Exception { assertEqual("medicinalproductinteraction-questionnaire.json"); }
    @Test @Tag("multi")  void medicinalproductinteraction_profile() throws Exception { assertEqual("medicinalproductinteraction.profile.json"); }
    @Test  void medicinalproductmanufactured_example() throws Exception { assertEqual("medicinalproductmanufactured-example.json"); }
    @Test  void medicinalproductmanufactured_questionnaire() throws Exception { assertEqual("medicinalproductmanufactured-questionnaire.json"); }
    @Test @Tag("multi")  void medicinalproductmanufactured_profile() throws Exception { assertEqual("medicinalproductmanufactured.profile.json"); }
    @Test  void medicinalproductpackaged_example() throws Exception { assertEqual("medicinalproductpackaged-example.json"); }
    @Test  void medicinalproductpackaged_questionnaire() throws Exception { assertEqual("medicinalproductpackaged-questionnaire.json"); }
    @Test @Tag("multi")  void medicinalproductpackaged_profile() throws Exception { assertEqual("medicinalproductpackaged.profile.json"); }
    @Test  void medicinalproductpharmaceutical_example() throws Exception { assertEqual("medicinalproductpharmaceutical-example.json"); }
    @Test  void medicinalproductpharmaceutical_questionnaire() throws Exception { assertEqual("medicinalproductpharmaceutical-questionnaire.json"); }
    @Test @Tag("multi")  void medicinalproductpharmaceutical_profile() throws Exception { assertEqual("medicinalproductpharmaceutical.profile.json"); }
    @Test  void medicinalproductundesirableeffect_example() throws Exception { assertEqual("medicinalproductundesirableeffect-example.json"); }
    @Test  void medicinalproductundesirableeffect_questionnaire() throws Exception { assertEqual("medicinalproductundesirableeffect-questionnaire.json"); }
    @Test @Tag("multi")  void medicinalproductundesirableeffect_profile() throws Exception { assertEqual("medicinalproductundesirableeffect.profile.json"); }
    @Test @Tag("bundle")  void message_request_link() throws Exception { assertEqual("message-request-link.json"); }
    @Test @Tag("bundle")  void message_response_link() throws Exception { assertEqual("message-response-link.json"); }
    @Test  void messagedefinition_example() throws Exception { assertEqual("messagedefinition-example.json"); }
    @Test  void messagedefinition_patient_link_notification() throws Exception { assertEqual("messagedefinition-patient-link-notification.json"); }
    @Test  void messagedefinition_patient_link_response() throws Exception { assertEqual("messagedefinition-patient-link-response.json"); }
    @Test  void messagedefinition_questionnaire() throws Exception { assertEqual("messagedefinition-questionnaire.json"); }
    @Test  void messagedefinition_profile() throws Exception { assertEqual("messagedefinition.profile.json"); }
    @Test  void messageheader_example() throws Exception { assertEqual("messageheader-example.json"); }
    @Test  void messageheader_questionnaire() throws Exception { assertEqual("messageheader-questionnaire.json"); }
    @Test  void messageheader_profile() throws Exception { assertEqual("messageheader.profile.json"); }
    @Test @Tag("multi")  void meta_profile() throws Exception { assertEqual("meta.profile.json"); }
    @Test  void metadataresource_profile() throws Exception { assertEqual("metadataresource.profile.json"); }
    @Test  void molecularsequence_example() throws Exception { assertEqual("molecularsequence-example.json"); }
    @Test  void molecularsequence_questionnaire() throws Exception { assertEqual("molecularsequence-questionnaire.json"); }
    @Test  void molecularsequence_profile() throws Exception { assertEqual("molecularsequence.profile.json"); }
    @Test  void money_profile() throws Exception { assertEqual("money.profile.json"); }
    @Test  void moneyquantity_profile() throws Exception { assertEqual("moneyquantity.profile.json"); }
    @Test  void namingsystem_example_id() throws Exception { assertEqual("namingsystem-example-id.json"); }
    @Test  void namingsystem_example() throws Exception { assertEqual("namingsystem-example.json"); }
    @Test  void namingsystem_questionnaire() throws Exception { assertEqual("namingsystem-questionnaire.json"); }
    @Test @Tag("bundle")  void namingsystem_registry() throws Exception { assertEqual("namingsystem-registry.json"); }
    @Test @Tag("bundle")  void namingsystem_terminologies() throws Exception { assertEqual("namingsystem-terminologies.json"); }
    @Test  void namingsystem_profile() throws Exception { assertEqual("namingsystem.profile.json"); }
    @Test  void narrative_profile() throws Exception { assertEqual("narrative.profile.json"); }
    @Test  void nutritionorder_example_cardiacdiet() throws Exception { assertEqual("nutritionorder-example-cardiacdiet.json"); }
    @Test  void nutritionorder_example_diabeticdiet() throws Exception { assertEqual("nutritionorder-example-diabeticdiet.json"); }
    @Test  void nutritionorder_example_diabeticsupplement() throws Exception { assertEqual("nutritionorder-example-diabeticsupplement.json"); }
    @Test  void nutritionorder_example_energysupplement() throws Exception { assertEqual("nutritionorder-example-energysupplement.json"); }
    @Test  void nutritionorder_example_enteralbolus() throws Exception { assertEqual("nutritionorder-example-enteralbolus.json"); }
    @Test  void nutritionorder_example_enteralcontinuous() throws Exception { assertEqual("nutritionorder-example-enteralcontinuous.json"); }
    @Test  void nutritionorder_example_fiberrestricteddiet() throws Exception { assertEqual("nutritionorder-example-fiberrestricteddiet.json"); }
    @Test  void nutritionorder_example_infantenteral() throws Exception { assertEqual("nutritionorder-example-infantenteral.json"); }
    @Test  void nutritionorder_example_proteinsupplement() throws Exception { assertEqual("nutritionorder-example-proteinsupplement.json"); }
    @Test  void nutritionorder_example_pureeddiet_simple() throws Exception { assertEqual("nutritionorder-example-pureeddiet-simple.json"); }
    @Test  void nutritionorder_example_pureeddiet() throws Exception { assertEqual("nutritionorder-example-pureeddiet.json"); }
    @Test  void nutritionorder_example_renaldiet() throws Exception { assertEqual("nutritionorder-example-renaldiet.json"); }
    @Test  void nutritionorder_example_texture_modified() throws Exception { assertEqual("nutritionorder-example-texture-modified.json"); }
    @Test  void nutritionorder_questionnaire() throws Exception { assertEqual("nutritionorder-questionnaire.json"); }
    @Test  void nutritionorder_profile() throws Exception { assertEqual("nutritionorder.profile.json"); }
    @Test  void observation_decimal() throws Exception { assertEqual("observation-decimal.json"); }
    @Test  void observation_example_10minute_apgar_score() throws Exception { assertEqual("observation-example-10minute-apgar-score.json"); }
    @Test  void observation_example_1minute_apgar_score() throws Exception { assertEqual("observation-example-1minute-apgar-score.json"); }
    @Test  void observation_example_20minute_apgar_score() throws Exception { assertEqual("observation-example-20minute-apgar-score.json"); }
    @Test  void observation_example_2minute_apgar_score() throws Exception { assertEqual("observation-example-2minute-apgar-score.json"); }
    @Test  void observation_example_5minute_apgar_score() throws Exception { assertEqual("observation-example-5minute-apgar-score.json"); }
    @Test  void observation_example_TPMT_diplotype() throws Exception { assertEqual("observation-example-TPMT-diplotype.json"); }
    @Test  void observation_example_TPMT_haplotype_one() throws Exception { assertEqual("observation-example-TPMT-haplotype-one.json"); }
    @Test  void observation_example_TPMT_haplotype_two() throws Exception { assertEqual("observation-example-TPMT-haplotype-two.json"); }
    @Test  void observation_example_abdo_tender() throws Exception { assertEqual("observation-example-abdo-tender.json"); }
    @Test  void observation_example_alcohol_type() throws Exception { assertEqual("observation-example-alcohol-type.json"); }
    @Test  void observation_example_bgpanel() throws Exception { assertEqual("observation-example-bgpanel.json"); }
    @Test  void observation_example_bloodgroup() throws Exception { assertEqual("observation-example-bloodgroup.json"); }
    @Test  void observation_example_bloodpressure_cancel() throws Exception { assertEqual("observation-example-bloodpressure-cancel.json"); }
    @Test  void observation_example_bloodpressure_dar() throws Exception { assertEqual("observation-example-bloodpressure-dar.json"); }
    @Test  void observation_example_bloodpressure() throws Exception { assertEqual("observation-example-bloodpressure.json"); }
    @Test  void observation_example_bmd() throws Exception { assertEqual("observation-example-bmd.json"); }
    @Test  void observation_example_bmi_using_related() throws Exception { assertEqual("observation-example-bmi-using-related.json"); }
    @Test  void observation_example_bmi() throws Exception { assertEqual("observation-example-bmi.json"); }
    @Test  void observation_example_body_height() throws Exception { assertEqual("observation-example-body-height.json"); }
    @Test  void observation_example_body_length() throws Exception { assertEqual("observation-example-body-length.json"); }
    @Test  void observation_example_body_temperature() throws Exception { assertEqual("observation-example-body-temperature.json"); }
    @Test  void observation_example_clinical_gender() throws Exception { assertEqual("observation-example-clinical-gender.json"); }
    @Test  void observation_example_date_lastmp() throws Exception { assertEqual("observation-example-date-lastmp.json"); }
    @Test  void observation_example_diplotype1() throws Exception { assertEqual("observation-example-diplotype1.json"); }
    @Test  void observation_example_eye_color() throws Exception { assertEqual("observation-example-eye-color.json"); }
    @Test  void observation_example_f001_glucose() throws Exception { assertEqual("observation-example-f001-glucose.json"); }
    @Test  void observation_example_f002_excess() throws Exception { assertEqual("observation-example-f002-excess.json"); }
    @Test  void observation_example_f003_co2() throws Exception { assertEqual("observation-example-f003-co2.json"); }
    @Test  void observation_example_f004_erythrocyte() throws Exception { assertEqual("observation-example-f004-erythrocyte.json"); }
    @Test  void observation_example_f005_hemoglobin() throws Exception { assertEqual("observation-example-f005-hemoglobin.json"); }
    @Test  void observation_example_f202_temperature() throws Exception { assertEqual("observation-example-f202-temperature.json"); }
    @Test  void observation_example_f203_bicarbonate() throws Exception { assertEqual("observation-example-f203-bicarbonate.json"); }
    @Test  void observation_example_f204_creatinine() throws Exception { assertEqual("observation-example-f204-creatinine.json"); }
    @Test  void observation_example_f205_egfr() throws Exception { assertEqual("observation-example-f205-egfr.json"); }
    @Test  void observation_example_f206_staphylococcus() throws Exception { assertEqual("observation-example-f206-staphylococcus.json"); }
    @Test  void observation_example_genetics_1() throws Exception { assertEqual("observation-example-genetics-1.json"); }
    @Test  void observation_example_genetics_2() throws Exception { assertEqual("observation-example-genetics-2.json"); }
    @Test  void observation_example_genetics_3() throws Exception { assertEqual("observation-example-genetics-3.json"); }
    @Test  void observation_example_genetics_4() throws Exception { assertEqual("observation-example-genetics-4.json"); }
    @Test  void observation_example_genetics_5() throws Exception { assertEqual("observation-example-genetics-5.json"); }
    @Test  void observation_example_genetics_brcapat() throws Exception { assertEqual("observation-example-genetics-brcapat.json"); }
    @Test  void observation_example_glasgow_qa() throws Exception { assertEqual("observation-example-glasgow-qa.json"); }
    @Test  void observation_example_glasgow() throws Exception { assertEqual("observation-example-glasgow.json"); }
    @Test  void observation_example_haplotype1() throws Exception { assertEqual("observation-example-haplotype1.json"); }
    @Test  void observation_example_haplotype2() throws Exception { assertEqual("observation-example-haplotype2.json"); }
    @Test  void observation_example_head_circumference() throws Exception { assertEqual("observation-example-head-circumference.json"); }
    @Test  void observation_example_heart_rate() throws Exception { assertEqual("observation-example-heart-rate.json"); }
    @Test  void observation_example_herd1() throws Exception { assertEqual("observation-example-herd1.json"); }
    @Test  void observation_example_map_sitting() throws Exception { assertEqual("observation-example-map-sitting.json"); }
    @Test  void observation_example_mbp() throws Exception { assertEqual("observation-example-mbp.json"); }
    @Test  void observation_example_phenotype() throws Exception { assertEqual("observation-example-phenotype.json"); }
    @Test  void observation_example_respiratory_rate() throws Exception { assertEqual("observation-example-respiratory-rate.json"); }
    @Test  void observation_example_rhstatus() throws Exception { assertEqual("observation-example-rhstatus.json"); }
    @Test  void observation_example_sample_data() throws Exception { assertEqual("observation-example-sample-data.json"); }
    @Test  void observation_example_satO2() throws Exception { assertEqual("observation-example-satO2.json"); }
    @Test  void observation_example_secondsmoke() throws Exception { assertEqual("observation-example-secondsmoke.json"); }
    @Test  void observation_example_spirometry() throws Exception { assertEqual("observation-example-spirometry.json"); }
    @Test  void observation_example_trachcare() throws Exception { assertEqual("observation-example-trachcare.json"); }
    @Test  void observation_example_unsat() throws Exception { assertEqual("observation-example-unsat.json"); }
    @Test  void observation_example_vitals_panel() throws Exception { assertEqual("observation-example-vitals-panel.json"); }
    @Test  void observation_example_vomiting() throws Exception { assertEqual("observation-example-vomiting.json"); }
    @Test  void observation_example_vp_oyster() throws Exception { assertEqual("observation-example-vp-oyster.json"); }
    @Test  void observation_example() throws Exception { assertEqual("observation-example.json"); }
    @Test  void observation_genetic_Observation_amino_acid_change() throws Exception { assertEqual("observation-genetic-Observation-amino-acid-change.json"); }
    @Test  void observation_genetic_Observation_dna_variant() throws Exception { assertEqual("observation-genetic-Observation-dna-variant.json"); }
    @Test  void observation_genetic_Observation_gene_amino_acid_change() throws Exception { assertEqual("observation-genetic-Observation-gene-amino-acid-change.json"); }
    @Test  void observation_genetic_Observation_gene_dnavariant() throws Exception { assertEqual("observation-genetic-Observation-gene-dnavariant.json"); }
    @Test  void observation_genetic_Observation_gene_identifier() throws Exception { assertEqual("observation-genetic-Observation-gene-identifier.json"); }
    @Test  void observation_genetics_questionnaire() throws Exception { assertEqual("observation-genetics-questionnaire.json"); }
    @Test  void observation_genetics_profile() throws Exception { assertEqual("observation-genetics.profile.json"); }
    @Test  void observation_questionnaire() throws Exception { assertEqual("observation-questionnaire.json"); }
    @Test  void observation_profile() throws Exception { assertEqual("observation.profile.json"); }
    @Test  void observationdefinition_example() throws Exception { assertEqual("observationdefinition-example.json"); }
    @Test  void observationdefinition_questionnaire() throws Exception { assertEqual("observationdefinition-questionnaire.json"); }
    @Test  void observationdefinition_profile() throws Exception { assertEqual("observationdefinition.profile.json"); }
    @Test  void oid_profile() throws Exception { assertEqual("oid.profile.json"); }
    @Test @Tag("multi")  void operation_activitydefinition_apply() throws Exception { assertEqual("operation-activitydefinition-apply.json"); }
    @Test  void operation_activitydefinition_data_requirements() throws Exception { assertEqual("operation-activitydefinition-data-requirements.json"); }
    @Test  void operation_capabilitystatement_conforms() throws Exception { assertEqual("operation-capabilitystatement-conforms.json"); }
    @Test  void operation_capabilitystatement_implements() throws Exception { assertEqual("operation-capabilitystatement-implements.json"); }
    @Test  void operation_capabilitystatement_subset() throws Exception { assertEqual("operation-capabilitystatement-subset.json"); }
    @Test  void operation_capabilitystatement_versions() throws Exception { assertEqual("operation-capabilitystatement-versions.json"); }
    @Test  void operation_chargeitemdefinition_apply() throws Exception { assertEqual("operation-chargeitemdefinition-apply.json"); }
    @Test  void operation_claim_submit() throws Exception { assertEqual("operation-claim-submit.json"); }
    @Test  void operation_codesystem_find_matches() throws Exception { assertEqual("operation-codesystem-find-matches.json"); }
    @Test @Tag("multi")  void operation_codesystem_lookup() throws Exception { assertEqual("operation-codesystem-lookup.json"); }
    @Test  void operation_codesystem_subsumes() throws Exception { assertEqual("operation-codesystem-subsumes.json"); }
    @Test @Tag("multi")  void operation_codesystem_validate_code() throws Exception { assertEqual("operation-codesystem-validate-code.json"); }
    @Test  void operation_composition_document() throws Exception { assertEqual("operation-composition-document.json"); }
    @Test  void operation_conceptmap_closure() throws Exception { assertEqual("operation-conceptmap-closure.json"); }
    @Test @Tag("multi")  void operation_conceptmap_translate() throws Exception { assertEqual("operation-conceptmap-translate.json"); }
    @Test  void operation_coverageeligibilityrequest_submit() throws Exception { assertEqual("operation-coverageeligibilityrequest-submit.json"); }
    @Test  void operation_encounter_everything() throws Exception { assertEqual("operation-encounter-everything.json"); }
    @Test  void operation_group_everything() throws Exception { assertEqual("operation-group-everything.json"); }
    @Test  void operation_library_data_requirements() throws Exception { assertEqual("operation-library-data-requirements.json"); }
    @Test  void operation_list_find() throws Exception { assertEqual("operation-list-find.json"); }
    @Test  void operation_measure_care_gaps() throws Exception { assertEqual("operation-measure-care-gaps.json"); }
    @Test  void operation_measure_collect_data() throws Exception { assertEqual("operation-measure-collect-data.json"); }
    @Test  void operation_measure_data_requirements() throws Exception { assertEqual("operation-measure-data-requirements.json"); }
    @Test  void operation_measure_evaluate_measure() throws Exception { assertEqual("operation-measure-evaluate-measure.json"); }
    @Test  void operation_measure_submit_data() throws Exception { assertEqual("operation-measure-submit-data.json"); }
    @Test  void operation_medicinalproduct_everything() throws Exception { assertEqual("operation-medicinalproduct-everything.json"); }
    @Test  void operation_messageheader_process_message() throws Exception { assertEqual("operation-messageheader-process-message.json"); }
    @Test  void operation_namingsystem_preferred_id() throws Exception { assertEqual("operation-namingsystem-preferred-id.json"); }
    @Test  void operation_observation_lastn() throws Exception { assertEqual("operation-observation-lastn.json"); }
    @Test @Tag("multi")  void operation_observation_stats() throws Exception { assertEqual("operation-observation-stats.json"); }
    @Test  void operation_patient_everything() throws Exception { assertEqual("operation-patient-everything.json"); }
    @Test  void operation_patient_match() throws Exception { assertEqual("operation-patient-match.json"); }
    @Test @Tag("multi")  void operation_plandefinition_apply() throws Exception { assertEqual("operation-plandefinition-apply.json"); }
    @Test  void operation_plandefinition_data_requirements() throws Exception { assertEqual("operation-plandefinition-data-requirements.json"); }
    @Test  void operation_resource_convert() throws Exception { assertEqual("operation-resource-convert.json"); }
    @Test  void operation_resource_graph() throws Exception { assertEqual("operation-resource-graph.json"); }
    @Test  void operation_resource_graphql() throws Exception { assertEqual("operation-resource-graphql.json"); }
    @Test  void operation_resource_meta_add() throws Exception { assertEqual("operation-resource-meta-add.json"); }
    @Test  void operation_resource_meta_delete() throws Exception { assertEqual("operation-resource-meta-delete.json"); }
    @Test  void operation_resource_meta() throws Exception { assertEqual("operation-resource-meta.json"); }
    @Test  void operation_resource_validate() throws Exception { assertEqual("operation-resource-validate.json"); }
    @Test  void operation_structuredefinition_questionnaire() throws Exception { assertEqual("operation-structuredefinition-questionnaire.json"); }
    @Test  void operation_structuredefinition_snapshot() throws Exception { assertEqual("operation-structuredefinition-snapshot.json"); }
    @Test  void operation_structuremap_transform() throws Exception { assertEqual("operation-structuremap-transform.json"); }
    @Test @Tag("multi")  void operation_valueset_expand() throws Exception { assertEqual("operation-valueset-expand.json"); }
    @Test @Tag("multi")  void operation_valueset_validate_code() throws Exception { assertEqual("operation-valueset-validate-code.json"); }
    @Test  void operationdefinition_example() throws Exception { assertEqual("operationdefinition-example.json"); }
    @Test  void operationdefinition_questionnaire() throws Exception { assertEqual("operationdefinition-questionnaire.json"); }
    @Test  void operationdefinition_profile() throws Exception { assertEqual("operationdefinition.profile.json"); }
    @Test  void operationoutcome_example_allok() throws Exception { assertEqual("operationoutcome-example-allok.json"); }
    @Test  void operationoutcome_example_break_the_glass() throws Exception { assertEqual("operationoutcome-example-break-the-glass.json"); }
    @Test  void operationoutcome_example_exception() throws Exception { assertEqual("operationoutcome-example-exception.json"); }
    @Test  void operationoutcome_example_searchfail() throws Exception { assertEqual("operationoutcome-example-searchfail.json"); }
    @Test  void operationoutcome_example_validationfail() throws Exception { assertEqual("operationoutcome-example-validationfail.json"); }
    @Test  void operationoutcome_example() throws Exception { assertEqual("operationoutcome-example.json"); }
    @Test  void operationoutcome_questionnaire() throws Exception { assertEqual("operationoutcome-questionnaire.json"); }
    @Test  void operationoutcome_profile() throws Exception { assertEqual("operationoutcome.profile.json"); }
    @Test  void organization_example_f001_burgers() throws Exception { assertEqual("organization-example-f001-burgers.json"); }
    @Test  void organization_example_f002_burgers_card() throws Exception { assertEqual("organization-example-f002-burgers-card.json"); }
    @Test  void organization_example_f003_burgers_ENT() throws Exception { assertEqual("organization-example-f003-burgers-ENT.json"); }
    @Test  void organization_example_f201_aumc() throws Exception { assertEqual("organization-example-f201-aumc.json"); }
    @Test  void organization_example_f203_bumc() throws Exception { assertEqual("organization-example-f203-bumc.json"); }
    @Test  void organization_example_gastro() throws Exception { assertEqual("organization-example-gastro.json"); }
    @Test  void organization_example_good_health_care() throws Exception { assertEqual("organization-example-good-health-care.json"); }
    @Test  void organization_example_hl7pay() throws Exception { assertEqual("organization-example-hl7pay.json"); }
    @Test  void organization_example_insurer() throws Exception { assertEqual("organization-example-insurer.json"); }
    @Test  void organization_example_lab() throws Exception { assertEqual("organization-example-lab.json"); }
    @Test  void organization_example_mihealth() throws Exception { assertEqual("organization-example-mihealth.json"); }
    @Test  void organization_example_mmanu() throws Exception { assertEqual("organization-example-mmanu.json"); }
    @Test  void organization_example() throws Exception { assertEqual("organization-example.json"); }
    @Test  void organization_questionnaire() throws Exception { assertEqual("organization-questionnaire.json"); }
    @Test  void organization_profile() throws Exception { assertEqual("organization.profile.json"); }
    @Test  void organizationaffiliation_example() throws Exception { assertEqual("organizationaffiliation-example.json"); }
    @Test  void organizationaffiliation_questionnaire() throws Exception { assertEqual("organizationaffiliation-questionnaire.json"); }
    @Test  void organizationaffiliation_profile() throws Exception { assertEqual("organizationaffiliation.profile.json"); }
    @Test  void orgrole_example_hie() throws Exception { assertEqual("orgrole-example-hie.json"); }
    @Test  void orgrole_example_services() throws Exception { assertEqual("orgrole-example-services.json"); }
    @Test  void oxygensat_questionnaire() throws Exception { assertEqual("oxygensat-questionnaire.json"); }
    @Test
    void oxygensat_profile() throws Exception { assertEqual("oxygensat.profile.json"); }

}
