package org.bayisehat.rdb2fhir.core.example.us;

import org.bayisehat.rdb2fhir.core.example.BaseExampleTest;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

public class USExampleGroup extends BaseExampleTest {

    @Test  void AllergyIntolerance_example() throws Exception { assertEqual("AllergyIntolerance-example.json"); }
    @Test  void Bundle_66c8856b_ba11_4876_8aa8_467aad8c11a2() throws Exception { assertEqual("Bundle-66c8856b-ba11-4876-8aa8-467aad8c11a2.json"); }
    @Test  void Bundle_c887e62f_6166_419f_8268_b5ecd6c7b901() throws Exception { assertEqual("Bundle-c887e62f-6166-419f-8268-b5ecd6c7b901.json"); }
    @Test  void Bundle_docref_example_1() throws Exception { assertEqual("Bundle-docref-example-1.json"); }
    @Test  void Bundle_docref_example_2() throws Exception { assertEqual("Bundle-docref-example-2.json"); }
    @Test @Tag("multi")  void CapabilityStatement_us_core_client() throws Exception { assertEqual("CapabilityStatement-us-core-client.json"); }
    @Test @Tag("multi")  void CapabilityStatement_us_core_server() throws Exception { assertEqual("CapabilityStatement-us-core-server.json"); }
    @Test  void CarePlan_colonoscopy() throws Exception { assertEqual("CarePlan-colonoscopy.json"); }
    @Test  void CareTeam_example() throws Exception { assertEqual("CareTeam-example.json"); }
    @Test  void CareTeam_missing_coded_data_example() throws Exception { assertEqual("CareTeam-missing-coded-data-example.json"); }
    @Test  void CodeSystem_careplan_category() throws Exception { assertEqual("CodeSystem-careplan-category.json"); }
    @Test  void CodeSystem_condition_category() throws Exception { assertEqual("CodeSystem-condition-category.json"); }
    @Test  void CodeSystem_us_core_category() throws Exception { assertEqual("CodeSystem-us-core-category.json"); }
    @Test  void CodeSystem_us_core_documentreference_category() throws Exception { assertEqual("CodeSystem-us-core-documentreference-category.json"); }
    @Test  void CodeSystem_us_core_provenance_participant_type() throws Exception { assertEqual("CodeSystem-us-core-provenance-participant-type.json"); }
    @Test  void Condition_condition_SDOH_example() throws Exception { assertEqual("Condition-condition-SDOH-example.json"); }
    @Test  void Condition_condition_duodenal_ulcer() throws Exception { assertEqual("Condition-condition-duodenal-ulcer.json"); }
    @Test  void Condition_encounter_diagnosis_example1() throws Exception { assertEqual("Condition-encounter-diagnosis-example1.json"); }
    @Test  void Condition_encounter_diagnosis_example2() throws Exception { assertEqual("Condition-encounter-diagnosis-example2.json"); }
    @Test  void Condition_health_concern_example() throws Exception { assertEqual("Condition-health-concern-example.json"); }
    @Test  void Coverage_coverage_example() throws Exception { assertEqual("Coverage-coverage-example.json"); }
    @Test  void Device_udi_1() throws Exception { assertEqual("Device-udi-1.json"); }
    @Test  void Device_udi_2() throws Exception { assertEqual("Device-udi-2.json"); }
    @Test  void Device_udi_3() throws Exception { assertEqual("Device-udi-3.json"); }
    @Test  void DiagnosticReport_bone_density_report() throws Exception { assertEqual("DiagnosticReport-bone-density-report.json"); }
    @Test @Tag("multi")  void DiagnosticReport_cardiology_report() throws Exception { assertEqual("DiagnosticReport-cardiology-report.json"); }
    @Test  void DiagnosticReport_cbc() throws Exception { assertEqual("DiagnosticReport-cbc.json"); }
    @Test  void DiagnosticReport_chest_xray_report() throws Exception { assertEqual("DiagnosticReport-chest-xray-report.json"); }
    @Test @Tag("multi")  void DiagnosticReport_metabolic_panel() throws Exception { assertEqual("DiagnosticReport-metabolic-panel.json"); }
    @Test  void DocumentReference_discharge_summary() throws Exception { assertEqual("DocumentReference-discharge-summary.json"); }
    @Test  void DocumentReference_episode_summary() throws Exception { assertEqual("DocumentReference-episode-summary.json"); }
    @Test  void Encounter_1036() throws Exception { assertEqual("Encounter-1036.json"); }
    @Test  void Encounter_delivery() throws Exception { assertEqual("Encounter-delivery.json"); }
    @Test  void Encounter_example_1() throws Exception { assertEqual("Encounter-example-1.json"); }
    @Test  void Goal_goal_1() throws Exception { assertEqual("Goal-goal-1.json"); }
    @Test  void Goal_goal_sdoh_2() throws Exception { assertEqual("Goal-goal-sdoh-2.json"); }
    @Test  void Immunization_imm_1() throws Exception { assertEqual("Immunization-imm-1.json"); }
    @Test  void ImplementationGuide_hl7_fhir_us_core() throws Exception { assertEqual("ImplementationGuide-hl7.fhir.us.core.json"); }
    @Test  void Location_hl7east() throws Exception { assertEqual("Location-hl7east.json"); }
    @Test  void Location_hospital() throws Exception { assertEqual("Location-hospital.json"); }
    @Test  void Media_chest_xray() throws Exception { assertEqual("Media-chest-xray.json"); }
    @Test  void Media_ekg_strip() throws Exception { assertEqual("Media-ekg-strip.json"); }
    @Test  void Medication_uscore_med1() throws Exception { assertEqual("Medication-uscore-med1.json"); }
    @Test  void Medication_uscore_med2() throws Exception { assertEqual("Medication-uscore-med2.json"); }
    @Test  void MedicationDispense_medicationdispense_example() throws Exception { assertEqual("MedicationDispense-medicationdispense-example.json"); }
    @Test  void MedicationRequest_medicationrequest_coded_oral_axid() throws Exception { assertEqual("MedicationRequest-medicationrequest-coded-oral-axid.json"); }
    @Test  void MedicationRequest_medicationrequest_contained_oral_axid() throws Exception { assertEqual("MedicationRequest-medicationrequest-contained-oral-axid.json"); }
    @Test  void MedicationRequest_medicationrequest_referenced_oral_axid() throws Exception { assertEqual("MedicationRequest-medicationrequest-referenced-oral-axid.json"); }
    @Test  void MedicationRequest_self_tylenol() throws Exception { assertEqual("MedicationRequest-self-tylenol.json"); }
    @Test  void Observation_10_minute_apgar_color() throws Exception { assertEqual("Observation-10-minute-apgar-color.json"); }
    @Test  void Observation_10_minute_apgar_heart_rate() throws Exception { assertEqual("Observation-10-minute-apgar-heart-rate.json"); }
    @Test  void Observation_10_minute_apgar_muscle_tone() throws Exception { assertEqual("Observation-10-minute-apgar-muscle-tone.json"); }
    @Test  void Observation_10_minute_apgar_reflex_irritability() throws Exception { assertEqual("Observation-10-minute-apgar-reflex-irritability.json"); }
    @Test  void Observation_10_minute_apgar_respiratory_effort() throws Exception { assertEqual("Observation-10-minute-apgar-respiratory-effort.json"); }
    @Test  void Observation_10_minute_apgar_score_panel() throws Exception { assertEqual("Observation-10-minute-apgar-score-panel.json"); }
    @Test  void Observation_10_minute_apgar_score() throws Exception { assertEqual("Observation-10-minute-apgar-score.json"); }
    @Test  void Observation_AHC_HRSN_item_example_68517_2() throws Exception { assertEqual("Observation-AHC-HRSN-item-example-68517-2.json"); }
    @Test  void Observation_HVS_item_example_88122_7() throws Exception { assertEqual("Observation-HVS-item-example-88122-7.json"); }
    @Test  void Observation_HVS_item_example_88123_5() throws Exception { assertEqual("Observation-HVS-item-example-88123-5.json"); }
    @Test  void Observation_HVS_item_example_88124_3() throws Exception { assertEqual("Observation-HVS-item-example-88124-3.json"); }
    @Test  void Observation_HVS_panel_example_88121_9() throws Exception { assertEqual("Observation-HVS-panel-example-88121-9.json"); }
    @Test  void Observation_PHQ9_item_example_44250_9() throws Exception { assertEqual("Observation-PHQ9-item-example-44250-9.json"); }
    @Test  void Observation_PHQ9_item_example_44251_7() throws Exception { assertEqual("Observation-PHQ9-item-example-44251-7.json"); }
    @Test  void Observation_PHQ9_item_example_44252_5() throws Exception { assertEqual("Observation-PHQ9-item-example-44252-5.json"); }
    @Test  void Observation_PHQ9_item_example_44253_3() throws Exception { assertEqual("Observation-PHQ9-item-example-44253-3.json"); }
    @Test  void Observation_PHQ9_item_example_44254_1() throws Exception { assertEqual("Observation-PHQ9-item-example-44254-1.json"); }
    @Test  void Observation_PHQ9_item_example_44255_8() throws Exception { assertEqual("Observation-PHQ9-item-example-44255-8.json"); }
    @Test  void Observation_PHQ9_item_example_44258_2() throws Exception { assertEqual("Observation-PHQ9-item-example-44258-2.json"); }
    @Test  void Observation_PHQ9_item_example_44259_0() throws Exception { assertEqual("Observation-PHQ9-item-example-44259-0.json"); }
    @Test  void Observation_PHQ9_item_example_44260_8() throws Exception { assertEqual("Observation-PHQ9-item-example-44260-8.json"); }
    @Test  void Observation_PHQ9_item_example_44261_6() throws Exception { assertEqual("Observation-PHQ9-item-example-44261-6.json"); }
    @Test  void Observation_PHQ9_item_example_69722_7() throws Exception { assertEqual("Observation-PHQ9-item-example-69722-7.json"); }
    @Test @Tag("multi")  void Observation_PHQ9_panel_example_44249_1() throws Exception { assertEqual("Observation-PHQ9-panel-example-44249-1.json"); }
    @Test  void Observation_PRAPARE_item_example_54899_0() throws Exception { assertEqual("Observation-PRAPARE-item-example-54899-0.json"); }
    @Test  void Observation_PRAPARE_item_example_56051_6() throws Exception { assertEqual("Observation-PRAPARE-item-example-56051-6.json"); }
    @Test  void Observation_PRAPARE_item_example_56799_0() throws Exception { assertEqual("Observation-PRAPARE-item-example-56799-0.json"); }
    @Test  void Observation_PRAPARE_item_example_63512_8() throws Exception { assertEqual("Observation-PRAPARE-item-example-63512-8.json"); }
    @Test  void Observation_PRAPARE_item_example_63586_2() throws Exception { assertEqual("Observation-PRAPARE-item-example-63586-2.json"); }
    @Test  void Observation_PRAPARE_item_example_67875_5() throws Exception { assertEqual("Observation-PRAPARE-item-example-67875-5.json"); }
    @Test  void Observation_PRAPARE_item_example_71802_3() throws Exception { assertEqual("Observation-PRAPARE-item-example-71802-3.json"); }
    @Test  void Observation_PRAPARE_item_example_76437_3() throws Exception { assertEqual("Observation-PRAPARE-item-example-76437-3.json"); }
    @Test  void Observation_PRAPARE_item_example_76501_6() throws Exception { assertEqual("Observation-PRAPARE-item-example-76501-6.json"); }
    @Test  void Observation_PRAPARE_item_example_82589_3() throws Exception { assertEqual("Observation-PRAPARE-item-example-82589-3.json"); }
    @Test  void Observation_PRAPARE_item_example_93026_3() throws Exception { assertEqual("Observation-PRAPARE-item-example-93026-3.json"); }
    @Test  void Observation_PRAPARE_item_example_93027_1() throws Exception { assertEqual("Observation-PRAPARE-item-example-93027-1.json"); }
    @Test  void Observation_PRAPARE_item_example_93028_9() throws Exception { assertEqual("Observation-PRAPARE-item-example-93028-9.json"); }
    @Test  void Observation_PRAPARE_item_example_93029_7() throws Exception { assertEqual("Observation-PRAPARE-item-example-93029-7.json"); }
    @Test  void Observation_PRAPARE_item_example_93030_5() throws Exception { assertEqual("Observation-PRAPARE-item-example-93030-5.json"); }
    @Test  void Observation_PRAPARE_item_example_93033_9() throws Exception { assertEqual("Observation-PRAPARE-item-example-93033-9.json"); }
    @Test  void Observation_PRAPARE_item_example_93034_7() throws Exception { assertEqual("Observation-PRAPARE-item-example-93034-7.json"); }
    @Test  void Observation_PRAPARE_item_example_93035_4() throws Exception { assertEqual("Observation-PRAPARE-item-example-93035-4.json"); }
    @Test  void Observation_PRAPARE_item_example_93038_8() throws Exception { assertEqual("Observation-PRAPARE-item-example-93038-8.json"); }
    @Test  void Observation_PRAPARE_multiselect_item_example_32624_9_answer0() throws Exception { assertEqual("Observation-PRAPARE-multiselect-item-example-32624-9-answer0.json"); }
    @Test  void Observation_PRAPARE_multiselect_item_example_32624_9_answer1() throws Exception { assertEqual("Observation-PRAPARE-multiselect-item-example-32624-9-answer1.json"); }
    @Test  void Observation_PRAPARE_multiselect_item_example_93031_3_answer0() throws Exception { assertEqual("Observation-PRAPARE-multiselect-item-example-93031-3-answer0.json"); }
    @Test  void Observation_PRAPARE_multiselect_item_example_93031_3_answer1() throws Exception { assertEqual("Observation-PRAPARE-multiselect-item-example-93031-3-answer1.json"); }
    @Test  void Observation_PRAPARE_panel_example_93025_5() throws Exception { assertEqual("Observation-PRAPARE-panel-example-93025-5.json"); }
    @Test  void Observation_PRAPARE_panel_example_93039_6() throws Exception { assertEqual("Observation-PRAPARE-panel-example-93039-6.json"); }
    @Test  void Observation_PRAPARE_panel_example_93040_4() throws Exception { assertEqual("Observation-PRAPARE-panel-example-93040-4.json"); }
    @Test  void Observation_PRAPARE_panel_example_93041_2() throws Exception { assertEqual("Observation-PRAPARE-panel-example-93041-2.json"); }
    @Test  void Observation_PRAPARE_panel_example_93042_0() throws Exception { assertEqual("Observation-PRAPARE-panel-example-93042-0.json"); }
    @Test  void Observation_PRAPARE_panel_example_93043_8() throws Exception { assertEqual("Observation-PRAPARE-panel-example-93043-8.json"); }
    @Test  void Observation_at_home_in_vitro_test() throws Exception { assertEqual("Observation-at-home-in-vitro-test.json"); }
    @Test  void Observation_blood_pressure() throws Exception { assertEqual("Observation-blood-pressure.json"); }
    @Test  void Observation_bmi() throws Exception { assertEqual("Observation-bmi.json"); }
    @Test  void Observation_bp_data_absent() throws Exception { assertEqual("Observation-bp-data-absent.json"); }
    @Test  void Observation_capillary_refill_time_nail_bed() throws Exception { assertEqual("Observation-capillary-refill-time-nail-bed.json"); }
    @Test  void Observation_cbc_erythrocytes() throws Exception { assertEqual("Observation-cbc-erythrocytes.json"); }
    @Test  void Observation_cbc_hematocrit() throws Exception { assertEqual("Observation-cbc-hematocrit.json"); }
    @Test  void Observation_cbc_hemoglobin() throws Exception { assertEqual("Observation-cbc-hemoglobin.json"); }
    @Test  void Observation_cbc_leukocytes() throws Exception { assertEqual("Observation-cbc-leukocytes.json"); }
    @Test  void Observation_cbc_mch() throws Exception { assertEqual("Observation-cbc-mch.json"); }
    @Test  void Observation_cbc_mchc() throws Exception { assertEqual("Observation-cbc-mchc.json"); }
    @Test  void Observation_cbc_mcv() throws Exception { assertEqual("Observation-cbc-mcv.json"); }
    @Test  void Observation_cbc_platelets() throws Exception { assertEqual("Observation-cbc-platelets.json"); }
    @Test  void Observation_dxa_femur_l_armass_bmd() throws Exception { assertEqual("Observation-dxa-femur-l-armass-bmd.json"); }
    @Test  void Observation_dxa_femur_l_t_score_bmd() throws Exception { assertEqual("Observation-dxa-femur-l-t-score-bmd.json"); }
    @Test  void Observation_dxa_femur_l_z_score_bmd() throws Exception { assertEqual("Observation-dxa-femur-l-z-score-bmd.json"); }
    @Test  void Observation_dxa_hip_l_armass_bmd() throws Exception { assertEqual("Observation-dxa-hip-l-armass-bmd.json"); }
    @Test  void Observation_dxa_hip_l_t_score_bmd() throws Exception { assertEqual("Observation-dxa-hip-l-t-score-bmd.json"); }
    @Test  void Observation_dxa_hip_l_z_score_bmd() throws Exception { assertEqual("Observation-dxa-hip-l-z-score-bmd.json"); }
    @Test  void Observation_ekg_impression() throws Exception { assertEqual("Observation-ekg-impression.json"); }
    @Test  void Observation_ekg_lead() throws Exception { assertEqual("Observation-ekg-lead.json"); }
    @Test  void Observation_head_circumference() throws Exception { assertEqual("Observation-head-circumference.json"); }
    @Test  void Observation_heart_rate_rhythm() throws Exception { assertEqual("Observation-heart-rate-rhythm.json"); }
    @Test  void Observation_heart_rate() throws Exception { assertEqual("Observation-heart-rate.json"); }
    @Test  void Observation_height() throws Exception { assertEqual("Observation-height.json"); }
    @Test  void Observation_jugular_vein_distension() throws Exception { assertEqual("Observation-jugular-vein-distension.json"); }
    @Test  void Observation_length() throws Exception { assertEqual("Observation-length.json"); }
    @Test  void Observation_observation_occupation_industry_unknown() throws Exception { assertEqual("Observation-observation-occupation-industry-unknown.json"); }
    @Test  void Observation_observation_occupation_unknown() throws Exception { assertEqual("Observation-observation-occupation-unknown.json"); }
    @Test  void Observation_observation_occupation() throws Exception { assertEqual("Observation-observation-occupation.json"); }
    @Test  void Observation_ofc_percentile() throws Exception { assertEqual("Observation-ofc-percentile.json"); }
    @Test  void Observation_oxygen_saturation() throws Exception { assertEqual("Observation-oxygen-saturation.json"); }
    @Test  void Observation_p_r_interval_ekg_lead() throws Exception { assertEqual("Observation-p-r-interval-ekg-lead.json"); }
    @Test  void Observation_pediatric_bmi_example() throws Exception { assertEqual("Observation-pediatric-bmi-example.json"); }
    @Test  void Observation_pediatric_wt_example() throws Exception { assertEqual("Observation-pediatric-wt-example.json"); }
    @Test  void Observation_pregnancy_intent() throws Exception { assertEqual("Observation-pregnancy-intent.json"); }
    @Test  void Observation_pregnancy_status() throws Exception { assertEqual("Observation-pregnancy-status.json"); }
    @Test  void Observation_pulse_intensity_palpation() throws Exception { assertEqual("Observation-pulse-intensity-palpation.json"); }
    @Test  void Observation_q_t_interval_ekg_lead() throws Exception { assertEqual("Observation-q-t-interval-ekg-lead.json"); }
    @Test  void Observation_qrs_dur_ekg_lead() throws Exception { assertEqual("Observation-qrs-dur-ekg-lead.json"); }
    @Test  void Observation_respiratory_rate() throws Exception { assertEqual("Observation-respiratory-rate.json"); }
    @Test  void Observation_satO2_fiO2() throws Exception { assertEqual("Observation-satO2-fiO2.json"); }
    @Test  void Observation_serum_bun() throws Exception { assertEqual("Observation-serum-bun.json"); }
    @Test  void Observation_serum_calcium() throws Exception { assertEqual("Observation-serum-calcium.json"); }
    @Test  void Observation_serum_chloride() throws Exception { assertEqual("Observation-serum-chloride.json"); }
    @Test  void Observation_serum_co2() throws Exception { assertEqual("Observation-serum-co2.json"); }
    @Test  void Observation_serum_creatinine() throws Exception { assertEqual("Observation-serum-creatinine.json"); }
    @Test  void Observation_serum_glucose() throws Exception { assertEqual("Observation-serum-glucose.json"); }
    @Test  void Observation_serum_potassium() throws Exception { assertEqual("Observation-serum-potassium.json"); }
    @Test  void Observation_serum_sodium() throws Exception { assertEqual("Observation-serum-sodium.json"); }
    @Test  void Observation_serum_total_bilirubin() throws Exception { assertEqual("Observation-serum-total-bilirubin.json"); }
    @Test  void Observation_sexual_orientation_example() throws Exception { assertEqual("Observation-sexual-orientation-example.json"); }
    @Test  void Observation_simple_observation_cognitive_status() throws Exception { assertEqual("Observation-simple-observation-cognitive-status.json"); }
    @Test  void Observation_simple_observation_disability_status() throws Exception { assertEqual("Observation-simple-observation-disability-status.json"); }
    @Test  void Observation_simple_observation_sdoh() throws Exception { assertEqual("Observation-simple-observation-sdoh.json"); }
    @Test  void Observation_some_day_smoker() throws Exception { assertEqual("Observation-some-day-smoker.json"); }
    @Test  void Observation_temperature() throws Exception { assertEqual("Observation-temperature.json"); }
    @Test  void Observation_urobilinogen() throws Exception { assertEqual("Observation-urobilinogen.json"); }
    @Test  void Observation_weight() throws Exception { assertEqual("Observation-weight.json"); }
    @Test  void Observation_xray_chest_findings() throws Exception { assertEqual("Observation-xray-chest-findings.json"); }
    @Test  void Observation_xray_chest_impression() throws Exception { assertEqual("Observation-xray-chest-impression.json"); }
    @Test  void OperationDefinition_docref() throws Exception { assertEqual("OperationDefinition-docref.json"); }
    @Test  void Organization_acme_lab() throws Exception { assertEqual("Organization-acme-lab.json"); }
    @Test  void Organization_acme_payer() throws Exception { assertEqual("Organization-acme-payer.json"); }
    @Test  void Organization_example_organization_2() throws Exception { assertEqual("Organization-example-organization-2.json"); }
    @Test  void Organization_holy_healthcare() throws Exception { assertEqual("Organization-holy-healthcare.json"); }
    @Test  void Organization_saint_luke_w_endpoint() throws Exception { assertEqual("Organization-saint-luke-w-endpoint.json"); }
    @Test  void Patient_child_example() throws Exception { assertEqual("Patient-child-example.json"); }
    @Test  void Patient_deceased_example() throws Exception { assertEqual("Patient-deceased-example.json"); }
    @Test  void Patient_example_targeted_provenance() throws Exception { assertEqual("Patient-example-targeted-provenance.json"); }
    @Test  void Patient_example() throws Exception { assertEqual("Patient-example.json"); }
    @Test  void Patient_infant_example() throws Exception { assertEqual("Patient-infant-example.json"); }
    @Test  void Practitioner_practitioner_1() throws Exception { assertEqual("Practitioner-practitioner-1.json"); }
    @Test  void Practitioner_practitioner_2() throws Exception { assertEqual("Practitioner-practitioner-2.json"); }
    @Test  void Practitioner_practitioner_pharmacist() throws Exception { assertEqual("Practitioner-practitioner-pharmacist.json"); }
    @Test  void Procedure_defib_implant() throws Exception { assertEqual("Procedure-defib-implant.json"); }
    @Test  void Procedure_rehab() throws Exception { assertEqual("Procedure-rehab.json"); }
    @Test  void Provenance_example_targeted_provenance() throws Exception { assertEqual("Provenance-example-targeted-provenance.json"); }
    @Test  void Questionnaire_hunger_vital_sign_example() throws Exception { assertEqual("Questionnaire-hunger-vital-sign-example.json"); }
    @Test  void Questionnaire_phq_9_example() throws Exception { assertEqual("Questionnaire-phq-9-example.json"); }
    @Test  void Questionnaire_prapare_example() throws Exception { assertEqual("Questionnaire-prapare-example.json"); }
    @Test  void QuestionnaireResponse_glascow_coma_score() throws Exception { assertEqual("QuestionnaireResponse-glascow-coma-score.json"); }
    @Test  void QuestionnaireResponse_hunger_vital_sign_example() throws Exception { assertEqual("QuestionnaireResponse-hunger-vital-sign-example.json"); }
    @Test void QuestionnaireResponse_phq_9_example() throws Exception { assertEqual("QuestionnaireResponse-phq-9-example.json"); } //
    @Test  void QuestionnaireResponse_prapare_example() throws Exception { assertEqual("QuestionnaireResponse-prapare-example.json"); }
    @Test  void RelatedPerson_shaw_niece() throws Exception { assertEqual("RelatedPerson-shaw-niece.json"); }
    @Test  void SearchParameter_us_core_allergyintolerance_clinical_status() throws Exception { assertEqual("SearchParameter-us-core-allergyintolerance-clinical-status.json"); }
    @Test  void SearchParameter_us_core_allergyintolerance_patient() throws Exception { assertEqual("SearchParameter-us-core-allergyintolerance-patient.json"); }
    @Test  void SearchParameter_us_core_careplan_category() throws Exception { assertEqual("SearchParameter-us-core-careplan-category.json"); }
    @Test  void SearchParameter_us_core_careplan_date() throws Exception { assertEqual("SearchParameter-us-core-careplan-date.json"); }
    @Test  void SearchParameter_us_core_careplan_patient() throws Exception { assertEqual("SearchParameter-us-core-careplan-patient.json"); }
    @Test  void SearchParameter_us_core_careplan_status() throws Exception { assertEqual("SearchParameter-us-core-careplan-status.json"); }
    @Test  void SearchParameter_us_core_careteam_patient() throws Exception { assertEqual("SearchParameter-us-core-careteam-patient.json"); }
    @Test  void SearchParameter_us_core_careteam_role() throws Exception { assertEqual("SearchParameter-us-core-careteam-role.json"); }
    @Test  void SearchParameter_us_core_careteam_status() throws Exception { assertEqual("SearchParameter-us-core-careteam-status.json"); }
    @Test   void SearchParameter_us_core_condition_abatement_date() throws Exception { assertEqual("SearchParameter-us-core-condition-abatement-date.json"); }
    @Test  void SearchParameter_us_core_condition_asserted_date() throws Exception { assertEqual("SearchParameter-us-core-condition-asserted-date.json"); }
    @Test  void SearchParameter_us_core_condition_category() throws Exception { assertEqual("SearchParameter-us-core-condition-category.json"); }
    @Test  void SearchParameter_us_core_condition_clinical_status() throws Exception { assertEqual("SearchParameter-us-core-condition-clinical-status.json"); }
    @Test  void SearchParameter_us_core_condition_code() throws Exception { assertEqual("SearchParameter-us-core-condition-code.json"); }
    @Test  void SearchParameter_us_core_condition_encounter() throws Exception { assertEqual("SearchParameter-us-core-condition-encounter.json"); }
    @Test  void SearchParameter_us_core_condition_onset_date() throws Exception { assertEqual("SearchParameter-us-core-condition-onset-date.json"); }
    @Test  void SearchParameter_us_core_condition_patient() throws Exception { assertEqual("SearchParameter-us-core-condition-patient.json"); }
    @Test  void SearchParameter_us_core_condition_recorded_date() throws Exception { assertEqual("SearchParameter-us-core-condition-recorded-date.json"); }
    @Test  void SearchParameter_us_core_coverage_patient() throws Exception { assertEqual("SearchParameter-us-core-coverage-patient.json"); }
    @Test  void SearchParameter_us_core_device_patient() throws Exception { assertEqual("SearchParameter-us-core-device-patient.json"); }
    @Test  void SearchParameter_us_core_device_status() throws Exception { assertEqual("SearchParameter-us-core-device-status.json"); }
    @Test  void SearchParameter_us_core_device_type() throws Exception { assertEqual("SearchParameter-us-core-device-type.json"); }
    @Test  void SearchParameter_us_core_diagnosticreport_category() throws Exception { assertEqual("SearchParameter-us-core-diagnosticreport-category.json"); }
    @Test  void SearchParameter_us_core_diagnosticreport_code() throws Exception { assertEqual("SearchParameter-us-core-diagnosticreport-code.json"); }
    @Test  void SearchParameter_us_core_diagnosticreport_date() throws Exception { assertEqual("SearchParameter-us-core-diagnosticreport-date.json"); }
    @Test  void SearchParameter_us_core_diagnosticreport_patient() throws Exception { assertEqual("SearchParameter-us-core-diagnosticreport-patient.json"); }
    @Test  void SearchParameter_us_core_diagnosticreport_status() throws Exception { assertEqual("SearchParameter-us-core-diagnosticreport-status.json"); }
    @Test  void SearchParameter_us_core_documentreference_category() throws Exception { assertEqual("SearchParameter-us-core-documentreference-category.json"); }
    @Test  void SearchParameter_us_core_documentreference_date() throws Exception { assertEqual("SearchParameter-us-core-documentreference-date.json"); }
    @Test  void SearchParameter_us_core_documentreference_id() throws Exception { assertEqual("SearchParameter-us-core-documentreference-id.json"); }
    @Test  void SearchParameter_us_core_documentreference_patient() throws Exception { assertEqual("SearchParameter-us-core-documentreference-patient.json"); }
    @Test  void SearchParameter_us_core_documentreference_period() throws Exception { assertEqual("SearchParameter-us-core-documentreference-period.json"); }
    @Test  void SearchParameter_us_core_documentreference_status() throws Exception { assertEqual("SearchParameter-us-core-documentreference-status.json"); }
    @Test  void SearchParameter_us_core_documentreference_type() throws Exception { assertEqual("SearchParameter-us-core-documentreference-type.json"); }
    @Test  void SearchParameter_us_core_encounter_class() throws Exception { assertEqual("SearchParameter-us-core-encounter-class.json"); }
    @Test  void SearchParameter_us_core_encounter_date() throws Exception { assertEqual("SearchParameter-us-core-encounter-date.json"); }
    @Test  void SearchParameter_us_core_encounter_discharge_disposition() throws Exception { assertEqual("SearchParameter-us-core-encounter-discharge-disposition.json"); }
    @Test  void SearchParameter_us_core_encounter_id() throws Exception { assertEqual("SearchParameter-us-core-encounter-id.json"); }
    @Test  void SearchParameter_us_core_encounter_identifier() throws Exception { assertEqual("SearchParameter-us-core-encounter-identifier.json"); }
    @Test  void SearchParameter_us_core_encounter_location() throws Exception { assertEqual("SearchParameter-us-core-encounter-location.json"); }
    @Test  void SearchParameter_us_core_encounter_patient() throws Exception { assertEqual("SearchParameter-us-core-encounter-patient.json"); }
    @Test  void SearchParameter_us_core_encounter_status() throws Exception { assertEqual("SearchParameter-us-core-encounter-status.json"); }
    @Test  void SearchParameter_us_core_encounter_type() throws Exception { assertEqual("SearchParameter-us-core-encounter-type.json"); }
    @Test  void SearchParameter_us_core_ethnicity() throws Exception { assertEqual("SearchParameter-us-core-ethnicity.json"); }
    @Test  void SearchParameter_us_core_goal_description() throws Exception { assertEqual("SearchParameter-us-core-goal-description.json"); }
    @Test  void SearchParameter_us_core_goal_lifecycle_status() throws Exception { assertEqual("SearchParameter-us-core-goal-lifecycle-status.json"); }
    @Test  void SearchParameter_us_core_goal_patient() throws Exception { assertEqual("SearchParameter-us-core-goal-patient.json"); }
    @Test   void SearchParameter_us_core_goal_target_date() throws Exception { assertEqual("SearchParameter-us-core-goal-target-date.json"); }
    @Test  void SearchParameter_us_core_immunization_date() throws Exception { assertEqual("SearchParameter-us-core-immunization-date.json"); }
    @Test  void SearchParameter_us_core_immunization_patient() throws Exception { assertEqual("SearchParameter-us-core-immunization-patient.json"); }
    @Test  void SearchParameter_us_core_immunization_status() throws Exception { assertEqual("SearchParameter-us-core-immunization-status.json"); }
    @Test  void SearchParameter_us_core_location_address_city() throws Exception { assertEqual("SearchParameter-us-core-location-address-city.json"); }
    @Test  void SearchParameter_us_core_location_address_postalcode() throws Exception { assertEqual("SearchParameter-us-core-location-address-postalcode.json"); }
    @Test  void SearchParameter_us_core_location_address_state() throws Exception { assertEqual("SearchParameter-us-core-location-address-state.json"); }
    @Test  void SearchParameter_us_core_location_address() throws Exception { assertEqual("SearchParameter-us-core-location-address.json"); }
    @Test  void SearchParameter_us_core_location_name() throws Exception { assertEqual("SearchParameter-us-core-location-name.json"); }
    @Test  void SearchParameter_us_core_medicationdispense_patient() throws Exception { assertEqual("SearchParameter-us-core-medicationdispense-patient.json"); }
    @Test  void SearchParameter_us_core_medicationdispense_status() throws Exception { assertEqual("SearchParameter-us-core-medicationdispense-status.json"); }
    @Test  void SearchParameter_us_core_medicationdispense_type() throws Exception { assertEqual("SearchParameter-us-core-medicationdispense-type.json"); }
    @Test  void SearchParameter_us_core_medicationrequest_authoredon() throws Exception { assertEqual("SearchParameter-us-core-medicationrequest-authoredon.json"); }
    @Test  void SearchParameter_us_core_medicationrequest_encounter() throws Exception { assertEqual("SearchParameter-us-core-medicationrequest-encounter.json"); }
    @Test  void SearchParameter_us_core_medicationrequest_intent() throws Exception { assertEqual("SearchParameter-us-core-medicationrequest-intent.json"); }
    @Test  void SearchParameter_us_core_medicationrequest_patient() throws Exception { assertEqual("SearchParameter-us-core-medicationrequest-patient.json"); }
    @Test  void SearchParameter_us_core_medicationrequest_status() throws Exception { assertEqual("SearchParameter-us-core-medicationrequest-status.json"); }
    @Test  void SearchParameter_us_core_observation_category() throws Exception { assertEqual("SearchParameter-us-core-observation-category.json"); }
    @Test  void SearchParameter_us_core_observation_code() throws Exception { assertEqual("SearchParameter-us-core-observation-code.json"); }
    @Test  void SearchParameter_us_core_observation_date() throws Exception { assertEqual("SearchParameter-us-core-observation-date.json"); }
    @Test  void SearchParameter_us_core_observation_patient() throws Exception { assertEqual("SearchParameter-us-core-observation-patient.json"); }
    @Test  void SearchParameter_us_core_observation_status() throws Exception { assertEqual("SearchParameter-us-core-observation-status.json"); }
    @Test  void SearchParameter_us_core_organization_address() throws Exception { assertEqual("SearchParameter-us-core-organization-address.json"); }
    @Test  void SearchParameter_us_core_organization_name() throws Exception { assertEqual("SearchParameter-us-core-organization-name.json"); }
    @Test  void SearchParameter_us_core_patient_birthdate() throws Exception { assertEqual("SearchParameter-us-core-patient-birthdate.json"); }
    @Test  void SearchParameter_us_core_patient_death_date() throws Exception { assertEqual("SearchParameter-us-core-patient-death-date.json"); }
    @Test  void SearchParameter_us_core_patient_family() throws Exception { assertEqual("SearchParameter-us-core-patient-family.json"); }
    @Test  void SearchParameter_us_core_patient_gender_identity() throws Exception { assertEqual("SearchParameter-us-core-patient-gender-identity.json"); }
    @Test  void SearchParameter_us_core_patient_gender() throws Exception { assertEqual("SearchParameter-us-core-patient-gender.json"); }
    @Test  void SearchParameter_us_core_patient_given() throws Exception { assertEqual("SearchParameter-us-core-patient-given.json"); }
    @Test  void SearchParameter_us_core_patient_id() throws Exception { assertEqual("SearchParameter-us-core-patient-id.json"); }
    @Test  void SearchParameter_us_core_patient_identifier() throws Exception { assertEqual("SearchParameter-us-core-patient-identifier.json"); }
    @Test  void SearchParameter_us_core_patient_name() throws Exception { assertEqual("SearchParameter-us-core-patient-name.json"); }
    @Test  void SearchParameter_us_core_practitioner_id() throws Exception { assertEqual("SearchParameter-us-core-practitioner-id.json"); }
    @Test  void SearchParameter_us_core_practitioner_identifier() throws Exception { assertEqual("SearchParameter-us-core-practitioner-identifier.json"); }
    @Test  void SearchParameter_us_core_practitioner_name() throws Exception { assertEqual("SearchParameter-us-core-practitioner-name.json"); }
    @Test  void SearchParameter_us_core_practitionerrole_practitioner() throws Exception { assertEqual("SearchParameter-us-core-practitionerrole-practitioner.json"); }
    @Test  void SearchParameter_us_core_practitionerrole_specialty() throws Exception { assertEqual("SearchParameter-us-core-practitionerrole-specialty.json"); }
    @Test  void SearchParameter_us_core_procedure_code() throws Exception { assertEqual("SearchParameter-us-core-procedure-code.json"); }
    @Test  void SearchParameter_us_core_procedure_date() throws Exception { assertEqual("SearchParameter-us-core-procedure-date.json"); }
    @Test  void SearchParameter_us_core_procedure_patient() throws Exception { assertEqual("SearchParameter-us-core-procedure-patient.json"); }
    @Test  void SearchParameter_us_core_procedure_status() throws Exception { assertEqual("SearchParameter-us-core-procedure-status.json"); }
    @Test  void SearchParameter_us_core_questionnaireresponse_authored() throws Exception { assertEqual("SearchParameter-us-core-questionnaireresponse-authored.json"); }
    @Test  void SearchParameter_us_core_questionnaireresponse_id() throws Exception { assertEqual("SearchParameter-us-core-questionnaireresponse-id.json"); }
    @Test  void SearchParameter_us_core_questionnaireresponse_patient() throws Exception { assertEqual("SearchParameter-us-core-questionnaireresponse-patient.json"); }
    @Test  void SearchParameter_us_core_questionnaireresponse_questionnaire() throws Exception { assertEqual("SearchParameter-us-core-questionnaireresponse-questionnaire.json"); }
    @Test  void SearchParameter_us_core_questionnaireresponse_status() throws Exception { assertEqual("SearchParameter-us-core-questionnaireresponse-status.json"); }
    @Test  void SearchParameter_us_core_race() throws Exception { assertEqual("SearchParameter-us-core-race.json"); }
    @Test  void SearchParameter_us_core_relatedperson_id() throws Exception { assertEqual("SearchParameter-us-core-relatedperson-id.json"); }
    @Test  void SearchParameter_us_core_relatedperson_name() throws Exception { assertEqual("SearchParameter-us-core-relatedperson-name.json"); }
    @Test  void SearchParameter_us_core_relatedperson_patient() throws Exception { assertEqual("SearchParameter-us-core-relatedperson-patient.json"); }
    @Test  void SearchParameter_us_core_servicerequest_authored() throws Exception { assertEqual("SearchParameter-us-core-servicerequest-authored.json"); }
    @Test  void SearchParameter_us_core_servicerequest_category() throws Exception { assertEqual("SearchParameter-us-core-servicerequest-category.json"); }
    @Test  void SearchParameter_us_core_servicerequest_code() throws Exception { assertEqual("SearchParameter-us-core-servicerequest-code.json"); }
    @Test  void SearchParameter_us_core_servicerequest_id() throws Exception { assertEqual("SearchParameter-us-core-servicerequest-id.json"); }
    @Test  void SearchParameter_us_core_servicerequest_patient() throws Exception { assertEqual("SearchParameter-us-core-servicerequest-patient.json"); }
    @Test  void SearchParameter_us_core_servicerequest_status() throws Exception { assertEqual("SearchParameter-us-core-servicerequest-status.json"); }
    @Test  void SearchParameter_us_core_specimen_id() throws Exception { assertEqual("SearchParameter-us-core-specimen-id.json"); }
    @Test  void SearchParameter_us_core_specimen_patient() throws Exception { assertEqual("SearchParameter-us-core-specimen-patient.json"); }
    @Test  void ServiceRequest_defib_implant() throws Exception { assertEqual("ServiceRequest-defib-implant.json"); }
    @Test  void ServiceRequest_foodpantry_referral() throws Exception { assertEqual("ServiceRequest-foodpantry-referral.json"); }
    @Test  void ServiceRequest_rehab() throws Exception { assertEqual("ServiceRequest-rehab.json"); }
    @Test  void Specimen_specimen_example_serum() throws Exception { assertEqual("Specimen-specimen-example-serum.json"); }
    @Test  void StructureDefinition_head_occipital_frontal_circumference_percentile() throws Exception { assertEqual("StructureDefinition-head-occipital-frontal-circumference-percentile.json"); }
    @Test  void StructureDefinition_pediatric_bmi_for_age() throws Exception { assertEqual("StructureDefinition-pediatric-bmi-for-age.json"); }
    @Test  void StructureDefinition_pediatric_weight_for_height() throws Exception { assertEqual("StructureDefinition-pediatric-weight-for-height.json"); }
    @Test  void StructureDefinition_us_core_allergyintolerance() throws Exception { assertEqual("StructureDefinition-us-core-allergyintolerance.json"); }
    @Test  void StructureDefinition_us_core_birthsex() throws Exception { assertEqual("StructureDefinition-us-core-birthsex.json"); }
    @Test  void StructureDefinition_us_core_blood_pressure() throws Exception { assertEqual("StructureDefinition-us-core-blood-pressure.json"); }
    @Test  void StructureDefinition_us_core_bmi() throws Exception { assertEqual("StructureDefinition-us-core-bmi.json"); }
    @Test  void StructureDefinition_us_core_body_height() throws Exception { assertEqual("StructureDefinition-us-core-body-height.json"); }
    @Test  void StructureDefinition_us_core_body_temperature() throws Exception { assertEqual("StructureDefinition-us-core-body-temperature.json"); }
    @Test  void StructureDefinition_us_core_body_weight() throws Exception { assertEqual("StructureDefinition-us-core-body-weight.json"); }
    @Test  void StructureDefinition_us_core_careplan() throws Exception { assertEqual("StructureDefinition-us-core-careplan.json"); }
    @Test  void StructureDefinition_us_core_careteam() throws Exception { assertEqual("StructureDefinition-us-core-careteam.json"); }
    @Test  void StructureDefinition_us_core_condition_encounter_diagnosis() throws Exception { assertEqual("StructureDefinition-us-core-condition-encounter-diagnosis.json"); }
    @Test  void StructureDefinition_us_core_condition_problems_health_concerns() throws Exception { assertEqual("StructureDefinition-us-core-condition-problems-health-concerns.json"); }
    @Test  void StructureDefinition_us_core_coverage() throws Exception { assertEqual("StructureDefinition-us-core-coverage.json"); }
    @Test  void StructureDefinition_us_core_diagnosticreport_lab() throws Exception { assertEqual("StructureDefinition-us-core-diagnosticreport-lab.json"); }
    @Test  void StructureDefinition_us_core_diagnosticreport_note() throws Exception { assertEqual("StructureDefinition-us-core-diagnosticreport-note.json"); }
    @Test  void StructureDefinition_us_core_direct() throws Exception { assertEqual("StructureDefinition-us-core-direct.json"); }
    @Test  void StructureDefinition_us_core_documentreference() throws Exception { assertEqual("StructureDefinition-us-core-documentreference.json"); }
    @Test  void StructureDefinition_us_core_encounter() throws Exception { assertEqual("StructureDefinition-us-core-encounter.json"); }
    @Test @Tag("multi")  void StructureDefinition_us_core_ethnicity() throws Exception { assertEqual("StructureDefinition-us-core-ethnicity.json"); }
    @Test  void StructureDefinition_us_core_extension_questionnaire_uri() throws Exception { assertEqual("StructureDefinition-us-core-extension-questionnaire-uri.json"); }
    @Test  void StructureDefinition_us_core_genderIdentity() throws Exception { assertEqual("StructureDefinition-us-core-genderIdentity.json"); }
    @Test  void StructureDefinition_us_core_goal() throws Exception { assertEqual("StructureDefinition-us-core-goal.json"); }
    @Test  void StructureDefinition_us_core_head_circumference() throws Exception { assertEqual("StructureDefinition-us-core-head-circumference.json"); }
    @Test  void StructureDefinition_us_core_heart_rate() throws Exception { assertEqual("StructureDefinition-us-core-heart-rate.json"); }
    @Test  void StructureDefinition_us_core_immunization() throws Exception { assertEqual("StructureDefinition-us-core-immunization.json"); }
    @Test  void StructureDefinition_us_core_implantable_device() throws Exception { assertEqual("StructureDefinition-us-core-implantable-device.json"); }
    @Test  void StructureDefinition_us_core_jurisdiction() throws Exception { assertEqual("StructureDefinition-us-core-jurisdiction.json"); }
    @Test  void StructureDefinition_us_core_location() throws Exception { assertEqual("StructureDefinition-us-core-location.json"); }
    @Test  void StructureDefinition_us_core_medication() throws Exception { assertEqual("StructureDefinition-us-core-medication.json"); }
    @Test  void StructureDefinition_us_core_medicationdispense() throws Exception { assertEqual("StructureDefinition-us-core-medicationdispense.json"); }
    @Test  void StructureDefinition_us_core_medicationrequest() throws Exception { assertEqual("StructureDefinition-us-core-medicationrequest.json"); }
    @Test  void StructureDefinition_us_core_observation_clinical_result() throws Exception { assertEqual("StructureDefinition-us-core-observation-clinical-result.json"); }
    @Test  void StructureDefinition_us_core_observation_lab() throws Exception { assertEqual("StructureDefinition-us-core-observation-lab.json"); }
    @Test  void StructureDefinition_us_core_observation_occupation() throws Exception { assertEqual("StructureDefinition-us-core-observation-occupation.json"); }
    @Test  void StructureDefinition_us_core_observation_pregnancyintent() throws Exception { assertEqual("StructureDefinition-us-core-observation-pregnancyintent.json"); }
    @Test  void StructureDefinition_us_core_observation_pregnancystatus() throws Exception { assertEqual("StructureDefinition-us-core-observation-pregnancystatus.json"); }
    @Test  void StructureDefinition_us_core_observation_screening_assessment() throws Exception { assertEqual("StructureDefinition-us-core-observation-screening-assessment.json"); }
    @Test  void StructureDefinition_us_core_observation_sexual_orientation() throws Exception { assertEqual("StructureDefinition-us-core-observation-sexual-orientation.json"); }
    @Test  void StructureDefinition_us_core_organization() throws Exception { assertEqual("StructureDefinition-us-core-organization.json"); }
    @Test  void StructureDefinition_us_core_patient() throws Exception { assertEqual("StructureDefinition-us-core-patient.json"); }
    @Test  void StructureDefinition_us_core_practitioner() throws Exception { assertEqual("StructureDefinition-us-core-practitioner.json"); }
    @Test  void StructureDefinition_us_core_practitionerrole() throws Exception { assertEqual("StructureDefinition-us-core-practitionerrole.json"); }
    @Test  void StructureDefinition_us_core_procedure() throws Exception { assertEqual("StructureDefinition-us-core-procedure.json"); }
    @Test  void StructureDefinition_us_core_provenance() throws Exception { assertEqual("StructureDefinition-us-core-provenance.json"); }
    @Test  void StructureDefinition_us_core_pulse_oximetry() throws Exception { assertEqual("StructureDefinition-us-core-pulse-oximetry.json"); }
    @Test  void StructureDefinition_us_core_questionnaireresponse() throws Exception { assertEqual("StructureDefinition-us-core-questionnaireresponse.json"); }
    @Test @Tag("multi")  void StructureDefinition_us_core_race() throws Exception { assertEqual("StructureDefinition-us-core-race.json"); }
    @Test  void StructureDefinition_us_core_relatedperson() throws Exception { assertEqual("StructureDefinition-us-core-relatedperson.json"); }
    @Test  void StructureDefinition_us_core_respiratory_rate() throws Exception { assertEqual("StructureDefinition-us-core-respiratory-rate.json"); }
    @Test  void StructureDefinition_us_core_servicerequest() throws Exception { assertEqual("StructureDefinition-us-core-servicerequest.json"); }
    @Test  void StructureDefinition_us_core_sex() throws Exception { assertEqual("StructureDefinition-us-core-sex.json"); }
    @Test  void StructureDefinition_us_core_simple_observation() throws Exception { assertEqual("StructureDefinition-us-core-simple-observation.json"); }
    @Test  void StructureDefinition_us_core_smokingstatus() throws Exception { assertEqual("StructureDefinition-us-core-smokingstatus.json"); }
    @Test  void StructureDefinition_us_core_specimen() throws Exception { assertEqual("StructureDefinition-us-core-specimen.json"); }
    @Test @Tag("multi")  void StructureDefinition_us_core_tribal_affiliation() throws Exception { assertEqual("StructureDefinition-us-core-tribal-affiliation.json"); }
    @Test  void StructureDefinition_us_core_vital_signs() throws Exception { assertEqual("StructureDefinition-us-core-vital-signs.json"); }
    @Test  void StructureDefinition_uscdi_requirement() throws Exception { assertEqual("StructureDefinition-uscdi-requirement.json"); }
    @Test  void ValueSet_birthsex() throws Exception { assertEqual("ValueSet-birthsex.json"); }
    @Test  void ValueSet_detailed_ethnicity() throws Exception { assertEqual("ValueSet-detailed-ethnicity.json"); }
    @Test  void ValueSet_detailed_race() throws Exception { assertEqual("ValueSet-detailed-race.json"); }
    @Test  void ValueSet_omb_ethnicity_category() throws Exception { assertEqual("ValueSet-omb-ethnicity-category.json"); }
    @Test  void ValueSet_omb_race_category() throws Exception { assertEqual("ValueSet-omb-race-category.json"); }
    @Test  void ValueSet_simple_language() throws Exception { assertEqual("ValueSet-simple-language.json"); }
    @Test  void ValueSet_simple_observation() throws Exception { assertEqual("ValueSet-simple-observation.json"); }
    @Test  void ValueSet_us_core_clinical_note_type() throws Exception { assertEqual("ValueSet-us-core-clinical-note-type.json"); }
    @Test  void ValueSet_us_core_clinical_result_observation_category() throws Exception { assertEqual("ValueSet-us-core-clinical-result-observation-category.json"); }
    @Test  void ValueSet_us_core_condition_code() throws Exception { assertEqual("ValueSet-us-core-condition-code.json"); }
    @Test  void ValueSet_us_core_diagnosticreport_category() throws Exception { assertEqual("ValueSet-us-core-diagnosticreport-category.json"); }
    @Test  void ValueSet_us_core_diagnosticreport_report_and_note_codes() throws Exception { assertEqual("ValueSet-us-core-diagnosticreport-report-and-note-codes.json"); }
    @Test  void ValueSet_us_core_discharge_disposition() throws Exception { assertEqual("ValueSet-us-core-discharge-disposition.json"); }
    @Test  void ValueSet_us_core_documentreference_category() throws Exception { assertEqual("ValueSet-us-core-documentreference-category.json"); }
    @Test  void ValueSet_us_core_documentreference_type() throws Exception { assertEqual("ValueSet-us-core-documentreference-type.json"); }
    @Test  void ValueSet_us_core_encounter_type() throws Exception { assertEqual("ValueSet-us-core-encounter-type.json"); }
    @Test  void ValueSet_us_core_goal_description() throws Exception { assertEqual("ValueSet-us-core-goal-description.json"); }
    @Test  void ValueSet_us_core_laboratory_test_codes() throws Exception { assertEqual("ValueSet-us-core-laboratory-test-codes.json"); }
    @Test  void ValueSet_us_core_narrative_status() throws Exception { assertEqual("ValueSet-us-core-narrative-status.json"); }
    @Test  void ValueSet_us_core_observation_smoking_status_status() throws Exception { assertEqual("ValueSet-us-core-observation-smoking-status-status.json"); }
    @Test  void ValueSet_us_core_observation_smokingstatus_max() throws Exception { assertEqual("ValueSet-us-core-observation-smokingstatus-max.json"); }
    @Test  void ValueSet_us_core_observation_value_codes() throws Exception { assertEqual("ValueSet-us-core-observation-value-codes.json"); }
    @Test  void ValueSet_us_core_pregnancy_intent() throws Exception { assertEqual("ValueSet-us-core-pregnancy-intent.json"); }
    @Test  void ValueSet_us_core_pregnancy_status() throws Exception { assertEqual("ValueSet-us-core-pregnancy-status.json"); }
    @Test  void ValueSet_us_core_problem_or_health_concern() throws Exception { assertEqual("ValueSet-us-core-problem-or-health-concern.json"); }
    @Test  void ValueSet_us_core_procedure_code() throws Exception { assertEqual("ValueSet-us-core-procedure-code.json"); }
    @Test  void ValueSet_us_core_provenance_participant_type() throws Exception { assertEqual("ValueSet-us-core-provenance-participant-type.json"); }
    @Test  void ValueSet_us_core_screening_assessment_condition_category() throws Exception { assertEqual("ValueSet-us-core-screening-assessment-condition-category.json"); }
    @Test  void ValueSet_us_core_screening_assessment_observation_category() throws Exception { assertEqual("ValueSet-us-core-screening-assessment-observation-category.json"); }
    @Test  void ValueSet_us_core_servicerequest_category() throws Exception { assertEqual("ValueSet-us-core-servicerequest-category.json"); }
    @Test  void ValueSet_us_core_sexual_orientation() throws Exception { assertEqual("ValueSet-us-core-sexual-orientation.json"); }
    @Test  void ValueSet_us_core_simple_observation_category() throws Exception { assertEqual("ValueSet-us-core-simple-observation-category.json"); }
    @Test  void ValueSet_us_core_smoking_status_observation_codes() throws Exception { assertEqual("ValueSet-us-core-smoking-status-observation-codes.json"); }
    @Test  void ValueSet_us_core_survey_codes() throws Exception { assertEqual("ValueSet-us-core-survey-codes.json"); }
    @Test  void ValueSet_us_core_usps_state() throws Exception { assertEqual("ValueSet-us-core-usps-state.json"); }
    @Test  void ValueSet_us_core_vital_signs() throws Exception { assertEqual("ValueSet-us-core-vital-signs.json"); }


}
